<h2>Cvičenie 3 - Práca s knižnicou <code>dplyr</code></h2>
        <p>Cieľom tretieho cvičenia je práca s dátovými rámcami pomocou klnižnice <code>dplyr</code>. Uvedené príkazy sa často využívajú v procese predspracovania dát. </p>
      
<p>Balík <code>dplyr</code> je jedným z najpopupárnejších balíkov v R. V tejto časti sa pozrieme na niekoľko 
        príkladov a tipov ako používať knižnicu <code>dplyr</code> na čistenie a trasformáciu dát. Pre inštaláciu zadajte </p>

In [1]:
install.packages("pillar")

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [2]:
install.packages("dplyr")

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [3]:
update.packages("dplyr")

In [ ]:
update.packages()

a načítajte knižnicu pomocou nasledujúceho príkazu:

In [3]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


##  Základné kombinácie dvoch tabuliek

In [12]:
#__________________ variables __________________________________________
df1 = data.frame(ID = c(1, 2, 3, 4, 5),
                 w = c('a', 'b', 'c', 'd', 'e'),
                 x = c(1, 1, 0, 0, 1),
                 y = rnorm(5),
                 z = letters[1:5])
df2 = data.frame(ID = c(1, 7, 3, 6, 8),
                 a = c('z', 'b', 'k', 'd', 'l'),
                 b = c(1, 2, 3, 0, 4),
                 c = rnorm(5),
                 d = letters[2:6])

In [13]:
inner_join(df1, df2, by = "ID")

  ID w x y        z a b c          d
1 1  a 1 0.765637 a z 1 -0.4517769 b
2 3  c 0 1.210858 c k 3  0.2913236 d

In [14]:
left_join(df1, df2, by = "ID")

  ID w x y          z a  b  c          d
1 1  a 1  0.7656370 a z   1 -0.4517769 b
2 2  b 1 -0.1055532 b NA NA         NA NA
3 3  c 0  1.2108576 c k   3  0.2913236 d
4 4  d 0 -0.6961282 d NA NA         NA NA
5 5  e 1 -0.5334987 e NA NA         NA NA

In [15]:
right_join(df1, df2, by = "ID")

  ID w  x  y        z  a b c           d
1 1  a   1 0.765637 a  z 1 -0.45177690 b
2 3  c   0 1.210858 c  k 3  0.29132359 d
3 7  NA NA       NA NA b 2 -0.47230575 c
4 6  NA NA       NA NA d 0 -1.05948787 e
5 8  NA NA       NA NA l 4  0.08487472 f

In [16]:
#___________________________ cases __________________________________________
x=c(1,2)
y=c(2,3)

intersect(x, y)
union(x, y)
setdiff(x, y)

[1] 2

[1] 1 2 3

[1] 1

In [17]:
#__________________ bind cols/rows __________________________________________
df1=data.frame(ID = 1:6,  x=letters[1:6])
df1
df2=data.frame(ID = 7:12, x=letters[7:12])
df2

  ID x
1 1  a
2 2  b
3 3  c
4 4  d
5 5  e
6 6  f

  ID x
1  7 g
2  8 h
3  9 i
4 10 j
5 11 k
6 12 l

In [18]:
bind_rows(df1,df2)  # ekvivalent xy = rbind(df1,df2)

   ID x
1   1 a
2   2 b
3   3 c
4   4 d
5   5 e
6   6 f
7   7 g
8   8 h
9   9 i
10 10 j
11 11 k
12 12 l

In [19]:
bind_cols(df1,df2)  # ekvivalent xy = cbind(df1,df2)

New names:
• `ID` -> `ID...1`
• `x` -> `x...2`
• `ID` -> `ID...3`
• `x` -> `x...4`

  ID...1 x...2 ID...3 x...4
1 1      a      7     g
2 2      b      8     h
3 3      c      9     i
4 4      d     10     j
5 5      e     11     k
6 6      f     12     l

<p> V nasledujúcich úlohách budeme využívať dáta, o fiktívnych príjmoch rôznych štátov od roku 2002 do 2015. 
<a href="https://raw.githubusercontent.com/deepanshu88/data/master/sampledata.csv" > Tento dataset</a> obsahuje 51 riadkov (pozorovaní)
a 16 stĺpcov (premenných).</p> 

<p> Dataset si načitajte pomocou nasledujúceho kódu: </p>

In [20]:
dataset = read.csv("https://raw.githubusercontent.com/deepanshu88/data/master/sampledata.csv")

  <p>Pri riešení jednotlivých úloh sa budeme stretávať s týmito logickými operátormi: </p>
  <table class="table table-bordered table-striped">
    <thead>
      <tr><th>Operátor</th><th> Popis</th></tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-nowrap"><code>==</code></td>
        <td>Rovná sa</td>
      </tr>
      <tr>
        <td class="text-nowrap"><code>%in%</code></td>
        <td>Výber viacerých položiek</td>
      </tr>
      <tr>
        <td class="text-nowrap"><code>&</code></td>
        <td>logický operátor AND</td>
        </tr>
        <tr>
          <td class="text-nowrap"><code>|</code></td>
          <td>logický operátor OR</td>
        </tr>
        <tr>
            <td class="text-nowrap"><code>!</code></td>
            <td>negácia NOT</td>
        </tr>
    </tbody>
  </table>

## 1. Manipulate Cases
    
  <p>Nasledujúca tabuľka obsahuje základné funkcie na prácu s riadkami:</p>
  <table class="table table-bordered table-striped">
    <thead>
      <tr><th>Funkcia </th><th> Popis</th></tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-nowrap"><code>sample_n(dataframe,n)</code></td>
        <td> Náhodný výber <samp>n</samp> riadkov </td>
      </tr>
      <tr>
        <td class="text-nowrap"><code>sample_frac(dataframe,n)</code></td>
        <td> Náhodný výber <samp>n %</samp> riadkov, <samp>n</samp> zadávame ako desatinné číslo </td>
      </tr>
      <tr>
        <td class="text-nowrap"><code>distict(daframe, variables , .keep_all)</code></td>
        <td> Odstránenie duplikátov:
          <ul>
          <li> <samp>variables</samp> podmieňuje odstránenie podľa atribútov 
            <li> <samp>.keep_all</samp> môže nadobúdať hodnotu <samp>TRUE</samp> alebo <samp>FALSE</samp> 
              a používa sana zachovanie všetkých ostatných premenných vo výstupnom dátovom rámci.
          </ul>
          </td>
        </tr>
        <tr>
          <td class="text-nowrap"><code>filter(dataframe, logical conditions)</code></td>
          <td>Výber podmnožiny údajov (riadkov) so zodpovedajúcimi logickými podmienkami</td>
        </tr>
        <tr>
          <td class="text-nowrap"><code>slice()</code></td>
          <td>Výber riadkov podľa polohy</td>
        </tr>
        <tr>
            <td class="text-nowrap"><code>arrange(dataframe, variable(s)_to_sort)</code></td>
            <td>Zoradenie údajov</td>
        </tr>
    </tbody>
  </table>

### Príklady:

<b> <li> výber riadkov </li></b>

In [21]:
sample_n(dataset, 3)

  Index State      Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008
1 W     Wisconsin  1788920 1518578 1289663 1436888 1251678 1721874 1980167
2 N     New Mexico 1819239 1226057 1935991 1124400 1723493 1475985 1237704
3 M     Maine      1582720 1678622 1208496 1912040 1438549 1330014 1295877
  Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1 1901394 1648755 1940943 1729177 1510119 1701650 1846238
2 1820856 1801430 1653384 1475715 1623388 1533494 1868612
3 1969163 1627262 1706080 1437088 1318546 1116792 1529233

In [22]:
sample_frac(dataset, 0.1)

  Index State          Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008
1 M     Mississippi    1983285 1292558 1631325 1943311 1354579 1731643 1428291
2 S     South Carolina 1631522 1803455 1425193 1458191 1538731 1825195 1250499
3 I     Illinois       1508356 1527440 1493029 1261353 1540274 1747614 1871645
4 A     Arizona        1742027 1968140 1377583 1782199 1102568 1109382 1752886
5 N     Nevada         1426117 1114500 1119707 1758830 1694526 1765826 1903270
  Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1 1568049 1383227 1629132 1988270 1907777 1649668 1991232
2 1864685 1345102 1116203 1532332 1591735 1188417 1110655
3 1658551 1422021 1751422 1696729 1915435 1645465 1583516
4 1554330 1300521 1130709 1907284 1363279 1525866 1647724
5 1231480 1526066 1143343 1980195 1283813 1225348 1903804

<b> <li> odstránenie duplicitných riadkov </li></b>

In [23]:
distinct(dataset)

   Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  A     Alabama              1296530 1317711 1118631 1492583 1107408 1440134
2  A     Alaska               1170302 1960378 1818085 1447852 1861639 1465841
3  A     Arizona              1742027 1968140 1377583 1782199 1102568 1109382
4  A     Arkansas             1485531 1994927 1119299 1947979 1669191 1801213
5  C     California           1685349 1675807 1889570 1480280 1735069 1812546
6  C     Colorado             1343824 1878473 1886149 1236697 1871471 1814218
7  C     Connecticut          1610512 1232844 1181949 1518933 1841266 1976976
8  D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
9  D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
10 F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
11 G     Georgia              1929009 1541565 1810773 1779091 1326846 1223770
12 H     Hawaii               1461570 1200280 1213993 1245931 1459383 1430465
13 I     Idaho                1353210 1438538 1739154 1541015 1122387 1772050
14 I     Illinois             1508356 1527440 1493029 1261353 1540274 1747614
15 I     Indiana              1776918 1734104 1269927 1204117 1848073 1129546
16 I     Iowa                 1499269 1444576 1576367 1388924 1554813 1452911
17 K     Kansas               1509054 1290700 1522230 1532094 1104256 1863278
18 K     Kentucky             1813878 1448846 1800760 1250524 1137913 1911227
19 L     Louisiana            1584734 1110625 1868456 1751920 1233709 1920301
20 M     Maine                1582720 1678622 1208496 1912040 1438549 1330014
21 M     Maryland             1579713 1404700 1849798 1397738 1310270 1789128
22 M     Massachusetts        1647582 1686259 1620601 1777250 1531641 1380529
23 M     Michigan             1295635 1149931 1601027 1340716 1729449 1567494
24 M     Minnesota            1729921 1675204 1903907 1561839 1985692 1148621
25 M     Mississippi          1983285 1292558 1631325 1943311 1354579 1731643
26 M     Missouri             1221316 1858368 1773451 1573967 1374863 1486197
27 M     Montana              1877154 1540099 1332722 1273327 1625721 1983568
28 N     Nebraska             1885081 1309769 1425527 1240465 1500594 1278272
29 N     Nevada               1426117 1114500 1119707 1758830 1694526 1765826
30 N     New Hampshire        1419776 1854370 1195119 1990062 1645430 1286967
31 N     New Jersey           1605532 1141514 1613550 1181452 1541327 1156804
32 N     New Mexico           1819239 1226057 1935991 1124400 1723493 1475985
33 N     New York             1395149 1611371 1170675 1446810 1426941 1463171
34 N     North Carolina       1616742 1292223 1482792 1532347 1158716 1827420
35 N     North Dakota         1618807 1510193 1876940 1443172 1425030 1868788
36 O     Ohio                 1802132 1648498 1441386 1670280 1534888 1314824
37 O     Oklahoma             1173918 1334639 1663622 1798714 1312574 1708245
38 O     Oregon               1794912 1726665 1805445 1133510 1502242 1419251
39 P     Pennsylvania         1320191 1446723 1218591 1122030 1971479 1563062
40 R     Rhode Island         1501744 1942942 1266657 1961923 1835983 1234040
41 S     South Carolina       1631522 1803455 1425193 1458191 1538731 1825195
42 S     South Dakota         1159037 1150689 1660148 1417141 1418586 1279134
43 T     Tennessee            1811867 1485909 1974179 1157059 1786132 1399191
44 T     Texas                1520591 1310777 1957713 1907326 1873544 1655483
45 U     Utah                 1771096 1195861 1979395 1241662 1437456 1859416
46 V     Vermont              1146902 1832249 1492704 1579265 1332048 1563537
47 V     Virginia             1134317 1163996 1891068 1853855 1708715 1197698
48 W     Washington           1977749 1687136 1199490 1163092 1334864 1621989
49 W     West Virginia        1677347 1380662 1176100 1888948 1922085 1740826
50 W     Wisconsin            1788920 1518578 1289663 1436888 1251678 1721874
51 W     Wyoming              1775190 1498098 1198212 1881688 1750527 1523124
   Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1  1945229 1944173 1237582 1440756 1186741 1852841 1558906 1916661
2  1551826 1436541 1629616 1230866 1512804 1985302 1580394 1979143
3  1752886 1554330 1300521 1130709 1907284 1363279 1525866 1647724
4  1188104 1628980 1669295 1928238 1216675 1591896 1360959 1329341
5  1487315 1663809 1624509 1639670 1921845 1156536 1388461 1644607
6  1875146 1752387 1913275 1665877 1491604 1178355 1383978 1330736
7  1764457 1972730 1968730 1945524 1228529 1582249 1503156 1718072
8  1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508
9  1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183
10 1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389
11 1773090 1630325 1145473 1851245 1850111 1887157 1259353 1725470
12 1919423 1928416 1330509 1902816 1695126 1517184 1948108 1150882
13 1335481 1748608 1436809 1456340 1643855 1312561 1713718 1757171
14 1871645 1658551 1422021 1751422 1696729 1915435 1645465 1583516
15 1139551 1883976 1999102 1559924 1905760 1129794 1988394 1467614
16 1317983 1150783 1751389 1992996 1501879 1173694 1431705 1641866
17 1949478 1561528 1550433 1465812 1882929 1410249 1930090 1385528
18 1301848 1956681 1350895 1512894 1916616 1878271 1722762 1913350
19 1185085 1124853 1498662 1210385 1234234 1287663 1908602 1403857
20 1295877 1969163 1627262 1706080 1437088 1318546 1116792 1529233
21 1112765 1967225 1486246 1872327 1175819 1314343 1979529 1569566
22 1978904 1567651 1761048 1658538 1482203 1731917 1669749 1963337
23 1990431 1575185 1267626 1274673 1709853 1815596 1965196 1646634
24 1328133 1890633 1995304 1575533 1910216 1972021 1515366 1864553
25 1428291 1568049 1383227 1629132 1988270 1907777 1649668 1991232
26 1735099 1800620 1164202 1425363 1800052 1698105 1767835 1996005
27 1251742 1592690 1350619 1520064 1185225 1465705 1110394 1125903
28 1140598 1270585 1128711 1187207 1569665 1690920 1459243 1802211
29 1903270 1231480 1526066 1143343 1980195 1283813 1225348 1903804
30 1762936 1763211 1265642 1704297 1131298 1197576 1242623 1963313
31 1568034 1357418 1443718 1390010 1202326 1100990 1850165 1183568
32 1237704 1820856 1801430 1653384 1475715 1623388 1533494 1868612
33 1732098 1426216 1604531 1683687 1500089 1718837 1619033 1367705
34 1267737 1116168 1791535 1553750 1472258 1104893 1596452 1229085
35 1720352 1671468 1534571 1271132 1430978 1529024 1563898 1604118
36 1516621 1511460 1585465 1887714 1227303 1840898 1880804 1573117
37 1256746 1853142 1673831 1822933 1674707 1900523 1956742 1307678
38 1482786 1862351 1103794 1935687 1905378 1522129 1509171 1893515
39 1274168 1571032 1433835 1483292 1290329 1475344 1931500 1668232
40 1151409 1993136 1983569 1781016 1909119 1531212 1990412 1611730
41 1250499 1864685 1345102 1116203 1532332 1591735 1188417 1110655
42 1171870 1852424 1554782 1647245 1811156 1147488 1302834 1136443
43 1826406 1326460 1231739 1469785 1849041 1560887 1349173 1162164
44 1785986 1827503 1447457 1978374 1882532 1698698 1646508 1705322
45 1939284 1915865 1619186 1288285 1108281 1123353 1801019 1729273
46 1123567 1618583 1326369 1792600 1714960 1146278 1282790 1565924
47 1803330 1590043 1516758 1171686 1262342 1647032 1706707 1850394
48 1545621 1555554 1179331 1150089 1775787 1273834 1387428 1377341
49 1238174 1539322 1539603 1872519 1462137 1683127 1204344 1198791
50 1980167 1901394 1648755 1940943 1729177 1510119 1701650 1846238
51 1587602 1504455 1282142 1881814 1673668 1994022 1204029 1853858

In [24]:
distinct(dataset, Index, .keep_all= TRUE)

   Index State          Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008
1  A     Alabama        1296530 1317711 1118631 1492583 1107408 1440134 1945229
2  C     California     1685349 1675807 1889570 1480280 1735069 1812546 1487315
3  D     Delaware       1330403 1268673 1706751 1403759 1441351 1300836 1762096
4  F     Florida        1964626 1468852 1419738 1362787 1339608 1278550 1756185
5  G     Georgia        1929009 1541565 1810773 1779091 1326846 1223770 1773090
6  H     Hawaii         1461570 1200280 1213993 1245931 1459383 1430465 1919423
7  I     Idaho          1353210 1438538 1739154 1541015 1122387 1772050 1335481
8  K     Kansas         1509054 1290700 1522230 1532094 1104256 1863278 1949478
9  L     Louisiana      1584734 1110625 1868456 1751920 1233709 1920301 1185085
10 M     Maine          1582720 1678622 1208496 1912040 1438549 1330014 1295877
11 N     Nebraska       1885081 1309769 1425527 1240465 1500594 1278272 1140598
12 O     Ohio           1802132 1648498 1441386 1670280 1534888 1314824 1516621
13 P     Pennsylvania   1320191 1446723 1218591 1122030 1971479 1563062 1274168
14 R     Rhode Island   1501744 1942942 1266657 1961923 1835983 1234040 1151409
15 S     South Carolina 1631522 1803455 1425193 1458191 1538731 1825195 1250499
16 T     Tennessee      1811867 1485909 1974179 1157059 1786132 1399191 1826406
17 U     Utah           1771096 1195861 1979395 1241662 1437456 1859416 1939284
18 V     Vermont        1146902 1832249 1492704 1579265 1332048 1563537 1123567
19 W     Washington     1977749 1687136 1199490 1163092 1334864 1621989 1545621
   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1  1944173 1237582 1440756 1186741 1852841 1558906 1916661
2  1663809 1624509 1639670 1921845 1156536 1388461 1644607
3  1553585 1370984 1318669 1984027 1671279 1803169 1627508
4  1818438 1198403 1497051 1131928 1107448 1407784 1170389
5  1630325 1145473 1851245 1850111 1887157 1259353 1725470
6  1928416 1330509 1902816 1695126 1517184 1948108 1150882
7  1748608 1436809 1456340 1643855 1312561 1713718 1757171
8  1561528 1550433 1465812 1882929 1410249 1930090 1385528
9  1124853 1498662 1210385 1234234 1287663 1908602 1403857
10 1969163 1627262 1706080 1437088 1318546 1116792 1529233
11 1270585 1128711 1187207 1569665 1690920 1459243 1802211
12 1511460 1585465 1887714 1227303 1840898 1880804 1573117
13 1571032 1433835 1483292 1290329 1475344 1931500 1668232
14 1993136 1983569 1781016 1909119 1531212 1990412 1611730
15 1864685 1345102 1116203 1532332 1591735 1188417 1110655
16 1326460 1231739 1469785 1849041 1560887 1349173 1162164
17 1915865 1619186 1288285 1108281 1123353 1801019 1729273
18 1618583 1326369 1792600 1714960 1146278 1282790 1565924
19 1555554 1179331 1150089 1775787 1273834 1387428 1377341

In [25]:
distinct(dataset, Index, .keep_all= FALSE)

   Index
1  A
2  C
3  D
4  F
5  G
6  H
7  I
8  K
9  L
10 M
11 N
12 O
13 P
14 R
15 S
16 T
17 U
18 V
19 W

<b> <li> filter rows / výber riadkov </li></b>

In [26]:
filter(dataset, Index == "A")

  Index State    Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008
1 A     Alabama  1296530 1317711 1118631 1492583 1107408 1440134 1945229
2 A     Alaska   1170302 1960378 1818085 1447852 1861639 1465841 1551826
3 A     Arizona  1742027 1968140 1377583 1782199 1102568 1109382 1752886
4 A     Arkansas 1485531 1994927 1119299 1947979 1669191 1801213 1188104
  Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1 1944173 1237582 1440756 1186741 1852841 1558906 1916661
2 1436541 1629616 1230866 1512804 1985302 1580394 1979143
3 1554330 1300521 1130709 1907284 1363279 1525866 1647724
4 1628980 1669295 1928238 1216675 1591896 1360959 1329341

In [27]:
filter(dataset, Index  %in% c("A", "C"))

  Index State       Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008
1 A     Alabama     1296530 1317711 1118631 1492583 1107408 1440134 1945229
2 A     Alaska      1170302 1960378 1818085 1447852 1861639 1465841 1551826
3 A     Arizona     1742027 1968140 1377583 1782199 1102568 1109382 1752886
4 A     Arkansas    1485531 1994927 1119299 1947979 1669191 1801213 1188104
5 C     California  1685349 1675807 1889570 1480280 1735069 1812546 1487315
6 C     Colorado    1343824 1878473 1886149 1236697 1871471 1814218 1875146
7 C     Connecticut 1610512 1232844 1181949 1518933 1841266 1976976 1764457
  Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1 1944173 1237582 1440756 1186741 1852841 1558906 1916661
2 1436541 1629616 1230866 1512804 1985302 1580394 1979143
3 1554330 1300521 1130709 1907284 1363279 1525866 1647724
4 1628980 1669295 1928238 1216675 1591896 1360959 1329341
5 1663809 1624509 1639670 1921845 1156536 1388461 1644607
6 1752387 1913275 1665877 1491604 1178355 1383978 1330736
7 1972730 1968730 1945524 1228529 1582249 1503156 1718072

In [28]:
filter(dataset, !Index %in% c("A", "C"))

   Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
2  D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
3  F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
4  G     Georgia              1929009 1541565 1810773 1779091 1326846 1223770
5  H     Hawaii               1461570 1200280 1213993 1245931 1459383 1430465
6  I     Idaho                1353210 1438538 1739154 1541015 1122387 1772050
7  I     Illinois             1508356 1527440 1493029 1261353 1540274 1747614
8  I     Indiana              1776918 1734104 1269927 1204117 1848073 1129546
9  I     Iowa                 1499269 1444576 1576367 1388924 1554813 1452911
10 K     Kansas               1509054 1290700 1522230 1532094 1104256 1863278
11 K     Kentucky             1813878 1448846 1800760 1250524 1137913 1911227
12 L     Louisiana            1584734 1110625 1868456 1751920 1233709 1920301
13 M     Maine                1582720 1678622 1208496 1912040 1438549 1330014
14 M     Maryland             1579713 1404700 1849798 1397738 1310270 1789128
15 M     Massachusetts        1647582 1686259 1620601 1777250 1531641 1380529
16 M     Michigan             1295635 1149931 1601027 1340716 1729449 1567494
17 M     Minnesota            1729921 1675204 1903907 1561839 1985692 1148621
18 M     Mississippi          1983285 1292558 1631325 1943311 1354579 1731643
19 M     Missouri             1221316 1858368 1773451 1573967 1374863 1486197
20 M     Montana              1877154 1540099 1332722 1273327 1625721 1983568
21 N     Nebraska             1885081 1309769 1425527 1240465 1500594 1278272
22 N     Nevada               1426117 1114500 1119707 1758830 1694526 1765826
23 N     New Hampshire        1419776 1854370 1195119 1990062 1645430 1286967
24 N     New Jersey           1605532 1141514 1613550 1181452 1541327 1156804
25 N     New Mexico           1819239 1226057 1935991 1124400 1723493 1475985
26 N     New York             1395149 1611371 1170675 1446810 1426941 1463171
27 N     North Carolina       1616742 1292223 1482792 1532347 1158716 1827420
28 N     North Dakota         1618807 1510193 1876940 1443172 1425030 1868788
29 O     Ohio                 1802132 1648498 1441386 1670280 1534888 1314824
30 O     Oklahoma             1173918 1334639 1663622 1798714 1312574 1708245
31 O     Oregon               1794912 1726665 1805445 1133510 1502242 1419251
32 P     Pennsylvania         1320191 1446723 1218591 1122030 1971479 1563062
33 R     Rhode Island         1501744 1942942 1266657 1961923 1835983 1234040
34 S     South Carolina       1631522 1803455 1425193 1458191 1538731 1825195
35 S     South Dakota         1159037 1150689 1660148 1417141 1418586 1279134
36 T     Tennessee            1811867 1485909 1974179 1157059 1786132 1399191
37 T     Texas                1520591 1310777 1957713 1907326 1873544 1655483
38 U     Utah                 1771096 1195861 1979395 1241662 1437456 1859416
39 V     Vermont              1146902 1832249 1492704 1579265 1332048 1563537
40 V     Virginia             1134317 1163996 1891068 1853855 1708715 1197698
41 W     Washington           1977749 1687136 1199490 1163092 1334864 1621989
42 W     West Virginia        1677347 1380662 1176100 1888948 1922085 1740826
43 W     Wisconsin            1788920 1518578 1289663 1436888 1251678 1721874
44 W     Wyoming              1775190 1498098 1198212 1881688 1750527 1523124
   Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1  1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508
2  1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183
3  1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389
4  1773090 1630325 1145473 1851245 1850111 1887157 1259353 1725470
5  1919423 1928416 1330509 1902816 1695126 1517184 1948108 1150882
6  1335481 1748608 1436809 1456340 1643855 1312561 1713718 1757171
7  1871645 1658551 1422021 1751422 1696729 1915435 1645465 1583516
8  1139551 1883976 1999102 1559924 1905760 1129794 1988394 1467614
9  1317983 1150783 1751389 1992996 1501879 1173694 1431705 1641866
10 1949478 1561528 1550433 1465812 1882929 1410249 1930090 1385528
11 1301848 1956681 1350895 1512894 1916616 1878271 1722762 1913350
12 1185085 1124853 1498662 1210385 1234234 1287663 1908602 1403857
13 1295877 1969163 1627262 1706080 1437088 1318546 1116792 1529233
14 1112765 1967225 1486246 1872327 1175819 1314343 1979529 1569566
15 1978904 1567651 1761048 1658538 1482203 1731917 1669749 1963337
16 1990431 1575185 1267626 1274673 1709853 1815596 1965196 1646634
17 1328133 1890633 1995304 1575533 1910216 1972021 1515366 1864553
18 1428291 1568049 1383227 1629132 1988270 1907777 1649668 1991232
19 1735099 1800620 1164202 1425363 1800052 1698105 1767835 1996005
20 1251742 1592690 1350619 1520064 1185225 1465705 1110394 1125903
21 1140598 1270585 1128711 1187207 1569665 1690920 1459243 1802211
22 1903270 1231480 1526066 1143343 1980195 1283813 1225348 1903804
23 1762936 1763211 1265642 1704297 1131298 1197576 1242623 1963313
24 1568034 1357418 1443718 1390010 1202326 1100990 1850165 1183568
25 1237704 1820856 1801430 1653384 1475715 1623388 1533494 1868612
26 1732098 1426216 1604531 1683687 1500089 1718837 1619033 1367705
27 1267737 1116168 1791535 1553750 1472258 1104893 1596452 1229085
28 1720352 1671468 1534571 1271132 1430978 1529024 1563898 1604118
29 1516621 1511460 1585465 1887714 1227303 1840898 1880804 1573117
30 1256746 1853142 1673831 1822933 1674707 1900523 1956742 1307678
31 1482786 1862351 1103794 1935687 1905378 1522129 1509171 1893515
32 1274168 1571032 1433835 1483292 1290329 1475344 1931500 1668232
33 1151409 1993136 1983569 1781016 1909119 1531212 1990412 1611730
34 1250499 1864685 1345102 1116203 1532332 1591735 1188417 1110655
35 1171870 1852424 1554782 1647245 1811156 1147488 1302834 1136443
36 1826406 1326460 1231739 1469785 1849041 1560887 1349173 1162164
37 1785986 1827503 1447457 1978374 1882532 1698698 1646508 1705322
38 1939284 1915865 1619186 1288285 1108281 1123353 1801019 1729273
39 1123567 1618583 1326369 1792600 1714960 1146278 1282790 1565924
40 1803330 1590043 1516758 1171686 1262342 1647032 1706707 1850394
41 1545621 1555554 1179331 1150089 1775787 1273834 1387428 1377341
42 1238174 1539322 1539603 1872519 1462137 1683127 1204344 1198791
43 1980167 1901394 1648755 1940943 1729177 1510119 1701650 1846238
44 1587602 1504455 1282142 1881814 1673668 1994022 1204029 1853858

In [29]:
filter(dataset, Index  %in% c("A", "C") & Y2002 >= 1300000 )

  Index State       Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008
1 A     Arizona     1742027 1968140 1377583 1782199 1102568 1109382 1752886
2 A     Arkansas    1485531 1994927 1119299 1947979 1669191 1801213 1188104
3 C     California  1685349 1675807 1889570 1480280 1735069 1812546 1487315
4 C     Colorado    1343824 1878473 1886149 1236697 1871471 1814218 1875146
5 C     Connecticut 1610512 1232844 1181949 1518933 1841266 1976976 1764457
  Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1 1554330 1300521 1130709 1907284 1363279 1525866 1647724
2 1628980 1669295 1928238 1216675 1591896 1360959 1329341
3 1663809 1624509 1639670 1921845 1156536 1388461 1644607
4 1752387 1913275 1665877 1491604 1178355 1383978 1330736
5 1972730 1968730 1945524 1228529 1582249 1503156 1718072

In [30]:
filter(dataset, Index  %in% c("A", "C") | Y2002 >= 1300000)

   Index State          Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008
1  A     Alabama        1296530 1317711 1118631 1492583 1107408 1440134 1945229
2  A     Alaska         1170302 1960378 1818085 1447852 1861639 1465841 1551826
3  A     Arizona        1742027 1968140 1377583 1782199 1102568 1109382 1752886
4  A     Arkansas       1485531 1994927 1119299 1947979 1669191 1801213 1188104
5  C     California     1685349 1675807 1889570 1480280 1735069 1812546 1487315
6  C     Colorado       1343824 1878473 1886149 1236697 1871471 1814218 1875146
7  C     Connecticut    1610512 1232844 1181949 1518933 1841266 1976976 1764457
8  D     Delaware       1330403 1268673 1706751 1403759 1441351 1300836 1762096
9  F     Florida        1964626 1468852 1419738 1362787 1339608 1278550 1756185
10 G     Georgia        1929009 1541565 1810773 1779091 1326846 1223770 1773090
11 H     Hawaii         1461570 1200280 1213993 1245931 1459383 1430465 1919423
12 I     Idaho          1353210 1438538 1739154 1541015 1122387 1772050 1335481
13 I     Illinois       1508356 1527440 1493029 1261353 1540274 1747614 1871645
14 I     Indiana        1776918 1734104 1269927 1204117 1848073 1129546 1139551
15 I     Iowa           1499269 1444576 1576367 1388924 1554813 1452911 1317983
16 K     Kansas         1509054 1290700 1522230 1532094 1104256 1863278 1949478
17 K     Kentucky       1813878 1448846 1800760 1250524 1137913 1911227 1301848
18 L     Louisiana      1584734 1110625 1868456 1751920 1233709 1920301 1185085
19 M     Maine          1582720 1678622 1208496 1912040 1438549 1330014 1295877
20 M     Maryland       1579713 1404700 1849798 1397738 1310270 1789128 1112765
21 M     Massachusetts  1647582 1686259 1620601 1777250 1531641 1380529 1978904
22 M     Minnesota      1729921 1675204 1903907 1561839 1985692 1148621 1328133
23 M     Mississippi    1983285 1292558 1631325 1943311 1354579 1731643 1428291
24 M     Montana        1877154 1540099 1332722 1273327 1625721 1983568 1251742
25 N     Nebraska       1885081 1309769 1425527 1240465 1500594 1278272 1140598
26 N     Nevada         1426117 1114500 1119707 1758830 1694526 1765826 1903270
27 N     New Hampshire  1419776 1854370 1195119 1990062 1645430 1286967 1762936
28 N     New Jersey     1605532 1141514 1613550 1181452 1541327 1156804 1568034
29 N     New Mexico     1819239 1226057 1935991 1124400 1723493 1475985 1237704
30 N     New York       1395149 1611371 1170675 1446810 1426941 1463171 1732098
31 N     North Carolina 1616742 1292223 1482792 1532347 1158716 1827420 1267737
32 N     North Dakota   1618807 1510193 1876940 1443172 1425030 1868788 1720352
33 O     Ohio           1802132 1648498 1441386 1670280 1534888 1314824 1516621
34 O     Oregon         1794912 1726665 1805445 1133510 1502242 1419251 1482786
35 P     Pennsylvania   1320191 1446723 1218591 1122030 1971479 1563062 1274168
36 R     Rhode Island   1501744 1942942 1266657 1961923 1835983 1234040 1151409
37 S     South Carolina 1631522 1803455 1425193 1458191 1538731 1825195 1250499
38 T     Tennessee      1811867 1485909 1974179 1157059 1786132 1399191 1826406
39 T     Texas          1520591 1310777 1957713 1907326 1873544 1655483 1785986
40 U     Utah           1771096 1195861 1979395 1241662 1437456 1859416 1939284
41 W     Washington     1977749 1687136 1199490 1163092 1334864 1621989 1545621
42 W     West Virginia  1677347 1380662 1176100 1888948 1922085 1740826 1238174
43 W     Wisconsin      1788920 1518578 1289663 1436888 1251678 1721874 1980167
44 W     Wyoming        1775190 1498098 1198212 1881688 1750527 1523124 1587602
   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1  1944173 1237582 1440756 1186741 1852841 1558906 1916661
2  1436541 1629616 1230866 1512804 1985302 1580394 1979143
3  1554330 1300521 1130709 1907284 1363279 1525866 1647724
4  1628980 1669295 1928238 1216675 1591896 1360959 1329341
5  1663809 1624509 1639670 1921845 1156536 1388461 1644607
6  1752387 1913275 1665877 1491604 1178355 1383978 1330736
7  1972730 1968730 1945524 1228529 1582249 1503156 1718072
8  1553585 1370984 1318669 1984027 1671279 1803169 1627508
9  1818438 1198403 1497051 1131928 1107448 1407784 1170389
10 1630325 1145473 1851245 1850111 1887157 1259353 1725470
11 1928416 1330509 1902816 1695126 1517184 1948108 1150882
12 1748608 1436809 1456340 1643855 1312561 1713718 1757171
13 1658551 1422021 1751422 1696729 1915435 1645465 1583516
14 1883976 1999102 1559924 1905760 1129794 1988394 1467614
15 1150783 1751389 1992996 1501879 1173694 1431705 1641866
16 1561528 1550433 1465812 1882929 1410249 1930090 1385528
17 1956681 1350895 1512894 1916616 1878271 1722762 1913350
18 1124853 1498662 1210385 1234234 1287663 1908602 1403857
19 1969163 1627262 1706080 1437088 1318546 1116792 1529233
20 1967225 1486246 1872327 1175819 1314343 1979529 1569566
21 1567651 1761048 1658538 1482203 1731917 1669749 1963337
22 1890633 1995304 1575533 1910216 1972021 1515366 1864553
23 1568049 1383227 1629132 1988270 1907777 1649668 1991232
24 1592690 1350619 1520064 1185225 1465705 1110394 1125903
25 1270585 1128711 1187207 1569665 1690920 1459243 1802211
26 1231480 1526066 1143343 1980195 1283813 1225348 1903804
27 1763211 1265642 1704297 1131298 1197576 1242623 1963313
28 1357418 1443718 1390010 1202326 1100990 1850165 1183568
29 1820856 1801430 1653384 1475715 1623388 1533494 1868612
30 1426216 1604531 1683687 1500089 1718837 1619033 1367705
31 1116168 1791535 1553750 1472258 1104893 1596452 1229085
32 1671468 1534571 1271132 1430978 1529024 1563898 1604118
33 1511460 1585465 1887714 1227303 1840898 1880804 1573117
34 1862351 1103794 1935687 1905378 1522129 1509171 1893515
35 1571032 1433835 1483292 1290329 1475344 1931500 1668232
36 1993136 1983569 1781016 1909119 1531212 1990412 1611730
37 1864685 1345102 1116203 1532332 1591735 1188417 1110655
38 1326460 1231739 1469785 1849041 1560887 1349173 1162164
39 1827503 1447457 1978374 1882532 1698698 1646508 1705322
40 1915865 1619186 1288285 1108281 1123353 1801019 1729273
41 1555554 1179331 1150089 1775787 1273834 1387428 1377341
42 1539322 1539603 1872519 1462137 1683127 1204344 1198791
43 1901394 1648755 1940943 1729177 1510119 1701650 1846238
44 1504455 1282142 1881814 1673668 1994022 1204029 1853858

<b> <li> výber riadkov podľa pozície </li></b>

In [31]:
slice(dataset,3:10)

  Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1 A     Arizona              1742027 1968140 1377583 1782199 1102568 1109382
2 A     Arkansas             1485531 1994927 1119299 1947979 1669191 1801213
3 C     California           1685349 1675807 1889570 1480280 1735069 1812546
4 C     Colorado             1343824 1878473 1886149 1236697 1871471 1814218
5 C     Connecticut          1610512 1232844 1181949 1518933 1841266 1976976
6 D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
7 D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
8 F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
  Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1 1752886 1554330 1300521 1130709 1907284 1363279 1525866 1647724
2 1188104 1628980 1669295 1928238 1216675 1591896 1360959 1329341
3 1487315 1663809 1624509 1639670 1921845 1156536 1388461 1644607
4 1875146 1752387 1913275 1665877 1491604 1178355 1383978 1330736
5 1764457 1972730 1968730 1945524 1228529 1582249 1503156 1718072
6 1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508
7 1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183
8 1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389

<b> <li> zoradanie riadkov </li></b>

In [32]:
arrange(dataset,Y2011)

   Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  S     South Carolina       1631522 1803455 1425193 1458191 1538731 1825195
2  A     Arizona              1742027 1968140 1377583 1782199 1102568 1109382
3  N     Nevada               1426117 1114500 1119707 1758830 1694526 1765826
4  W     Washington           1977749 1687136 1199490 1163092 1334864 1621989
5  V     Virginia             1134317 1163996 1891068 1853855 1708715 1197698
6  N     Nebraska             1885081 1309769 1425527 1240465 1500594 1278272
7  L     Louisiana            1584734 1110625 1868456 1751920 1233709 1920301
8  A     Alaska               1170302 1960378 1818085 1447852 1861639 1465841
9  N     North Dakota         1618807 1510193 1876940 1443172 1425030 1868788
10 M     Michigan             1295635 1149931 1601027 1340716 1729449 1567494
11 U     Utah                 1771096 1195861 1979395 1241662 1437456 1859416
12 D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
13 D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
14 N     New Jersey           1605532 1141514 1613550 1181452 1541327 1156804
15 M     Missouri             1221316 1858368 1773451 1573967 1374863 1486197
16 A     Alabama              1296530 1317711 1118631 1492583 1107408 1440134
17 I     Idaho                1353210 1438538 1739154 1541015 1122387 1772050
18 K     Kansas               1509054 1290700 1522230 1532094 1104256 1863278
19 T     Tennessee            1811867 1485909 1974179 1157059 1786132 1399191
20 P     Pennsylvania         1320191 1446723 1218591 1122030 1971479 1563062
21 F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
22 K     Kentucky             1813878 1448846 1800760 1250524 1137913 1911227
23 M     Montana              1877154 1540099 1332722 1273327 1625721 1983568
24 N     North Carolina       1616742 1292223 1482792 1532347 1158716 1827420
25 I     Indiana              1776918 1734104 1269927 1204117 1848073 1129546
26 M     Minnesota            1729921 1675204 1903907 1561839 1985692 1148621
27 M     Mississippi          1983285 1292558 1631325 1943311 1354579 1731643
28 C     California           1685349 1675807 1889570 1480280 1735069 1812546
29 S     South Dakota         1159037 1150689 1660148 1417141 1418586 1279134
30 N     New Mexico           1819239 1226057 1935991 1124400 1723493 1475985
31 M     Massachusetts        1647582 1686259 1620601 1777250 1531641 1380529
32 C     Colorado             1343824 1878473 1886149 1236697 1871471 1814218
33 N     New York             1395149 1611371 1170675 1446810 1426941 1463171
34 N     New Hampshire        1419776 1854370 1195119 1990062 1645430 1286967
35 M     Maine                1582720 1678622 1208496 1912040 1438549 1330014
36 I     Illinois             1508356 1527440 1493029 1261353 1540274 1747614
37 R     Rhode Island         1501744 1942942 1266657 1961923 1835983 1234040
38 V     Vermont              1146902 1832249 1492704 1579265 1332048 1563537
39 O     Oklahoma             1173918 1334639 1663622 1798714 1312574 1708245
40 G     Georgia              1929009 1541565 1810773 1779091 1326846 1223770
41 M     Maryland             1579713 1404700 1849798 1397738 1310270 1789128
42 W     West Virginia        1677347 1380662 1176100 1888948 1922085 1740826
43 W     Wyoming              1775190 1498098 1198212 1881688 1750527 1523124
44 O     Ohio                 1802132 1648498 1441386 1670280 1534888 1314824
45 H     Hawaii               1461570 1200280 1213993 1245931 1459383 1430465
46 A     Arkansas             1485531 1994927 1119299 1947979 1669191 1801213
47 O     Oregon               1794912 1726665 1805445 1133510 1502242 1419251
48 W     Wisconsin            1788920 1518578 1289663 1436888 1251678 1721874
49 C     Connecticut          1610512 1232844 1181949 1518933 1841266 1976976
50 T     Texas                1520591 1310777 1957713 1907326 1873544 1655483
51 I     Iowa                 1499269 1444576 1576367 1388924 1554813 1452911
   Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1  1250499 1864685 1345102 1116203 1532332 1591735 1188417 1110655
2  1752886 1554330 1300521 1130709 1907284 1363279 1525866 1647724
3  1903270 1231480 1526066 1143343 1980195 1283813 1225348 1903804
4  1545621 1555554 1179331 1150089 1775787 1273834 1387428 1377341
5  1803330 1590043 1516758 1171686 1262342 1647032 1706707 1850394
6  1140598 1270585 1128711 1187207 1569665 1690920 1459243 1802211
7  1185085 1124853 1498662 1210385 1234234 1287663 1908602 1403857
8  1551826 1436541 1629616 1230866 1512804 1985302 1580394 1979143
9  1720352 1671468 1534571 1271132 1430978 1529024 1563898 1604118
10 1990431 1575185 1267626 1274673 1709853 1815596 1965196 1646634
11 1939284 1915865 1619186 1288285 1108281 1123353 1801019 1729273
12 1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508
13 1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183
14 1568034 1357418 1443718 1390010 1202326 1100990 1850165 1183568
15 1735099 1800620 1164202 1425363 1800052 1698105 1767835 1996005
16 1945229 1944173 1237582 1440756 1186741 1852841 1558906 1916661
17 1335481 1748608 1436809 1456340 1643855 1312561 1713718 1757171
18 1949478 1561528 1550433 1465812 1882929 1410249 1930090 1385528
19 1826406 1326460 1231739 1469785 1849041 1560887 1349173 1162164
20 1274168 1571032 1433835 1483292 1290329 1475344 1931500 1668232
21 1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389
22 1301848 1956681 1350895 1512894 1916616 1878271 1722762 1913350
23 1251742 1592690 1350619 1520064 1185225 1465705 1110394 1125903
24 1267737 1116168 1791535 1553750 1472258 1104893 1596452 1229085
25 1139551 1883976 1999102 1559924 1905760 1129794 1988394 1467614
26 1328133 1890633 1995304 1575533 1910216 1972021 1515366 1864553
27 1428291 1568049 1383227 1629132 1988270 1907777 1649668 1991232
28 1487315 1663809 1624509 1639670 1921845 1156536 1388461 1644607
29 1171870 1852424 1554782 1647245 1811156 1147488 1302834 1136443
30 1237704 1820856 1801430 1653384 1475715 1623388 1533494 1868612
31 1978904 1567651 1761048 1658538 1482203 1731917 1669749 1963337
32 1875146 1752387 1913275 1665877 1491604 1178355 1383978 1330736
33 1732098 1426216 1604531 1683687 1500089 1718837 1619033 1367705
34 1762936 1763211 1265642 1704297 1131298 1197576 1242623 1963313
35 1295877 1969163 1627262 1706080 1437088 1318546 1116792 1529233
36 1871645 1658551 1422021 1751422 1696729 1915435 1645465 1583516
37 1151409 1993136 1983569 1781016 1909119 1531212 1990412 1611730
38 1123567 1618583 1326369 1792600 1714960 1146278 1282790 1565924
39 1256746 1853142 1673831 1822933 1674707 1900523 1956742 1307678
40 1773090 1630325 1145473 1851245 1850111 1887157 1259353 1725470
41 1112765 1967225 1486246 1872327 1175819 1314343 1979529 1569566
42 1238174 1539322 1539603 1872519 1462137 1683127 1204344 1198791
43 1587602 1504455 1282142 1881814 1673668 1994022 1204029 1853858
44 1516621 1511460 1585465 1887714 1227303 1840898 1880804 1573117
45 1919423 1928416 1330509 1902816 1695126 1517184 1948108 1150882
46 1188104 1628980 1669295 1928238 1216675 1591896 1360959 1329341
47 1482786 1862351 1103794 1935687 1905378 1522129 1509171 1893515
48 1980167 1901394 1648755 1940943 1729177 1510119 1701650 1846238
49 1764457 1972730 1968730 1945524 1228529 1582249 1503156 1718072
50 1785986 1827503 1447457 1978374 1882532 1698698 1646508 1705322
51 1317983 1150783 1751389 1992996 1501879 1173694 1431705 1641866

In [33]:
arrange(dataset, desc(Y2011))

   Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  I     Iowa                 1499269 1444576 1576367 1388924 1554813 1452911
2  T     Texas                1520591 1310777 1957713 1907326 1873544 1655483
3  C     Connecticut          1610512 1232844 1181949 1518933 1841266 1976976
4  W     Wisconsin            1788920 1518578 1289663 1436888 1251678 1721874
5  O     Oregon               1794912 1726665 1805445 1133510 1502242 1419251
6  A     Arkansas             1485531 1994927 1119299 1947979 1669191 1801213
7  H     Hawaii               1461570 1200280 1213993 1245931 1459383 1430465
8  O     Ohio                 1802132 1648498 1441386 1670280 1534888 1314824
9  W     Wyoming              1775190 1498098 1198212 1881688 1750527 1523124
10 W     West Virginia        1677347 1380662 1176100 1888948 1922085 1740826
11 M     Maryland             1579713 1404700 1849798 1397738 1310270 1789128
12 G     Georgia              1929009 1541565 1810773 1779091 1326846 1223770
13 O     Oklahoma             1173918 1334639 1663622 1798714 1312574 1708245
14 V     Vermont              1146902 1832249 1492704 1579265 1332048 1563537
15 R     Rhode Island         1501744 1942942 1266657 1961923 1835983 1234040
16 I     Illinois             1508356 1527440 1493029 1261353 1540274 1747614
17 M     Maine                1582720 1678622 1208496 1912040 1438549 1330014
18 N     New Hampshire        1419776 1854370 1195119 1990062 1645430 1286967
19 N     New York             1395149 1611371 1170675 1446810 1426941 1463171
20 C     Colorado             1343824 1878473 1886149 1236697 1871471 1814218
21 M     Massachusetts        1647582 1686259 1620601 1777250 1531641 1380529
22 N     New Mexico           1819239 1226057 1935991 1124400 1723493 1475985
23 S     South Dakota         1159037 1150689 1660148 1417141 1418586 1279134
24 C     California           1685349 1675807 1889570 1480280 1735069 1812546
25 M     Mississippi          1983285 1292558 1631325 1943311 1354579 1731643
26 M     Minnesota            1729921 1675204 1903907 1561839 1985692 1148621
27 I     Indiana              1776918 1734104 1269927 1204117 1848073 1129546
28 N     North Carolina       1616742 1292223 1482792 1532347 1158716 1827420
29 M     Montana              1877154 1540099 1332722 1273327 1625721 1983568
30 K     Kentucky             1813878 1448846 1800760 1250524 1137913 1911227
31 F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
32 P     Pennsylvania         1320191 1446723 1218591 1122030 1971479 1563062
33 T     Tennessee            1811867 1485909 1974179 1157059 1786132 1399191
34 K     Kansas               1509054 1290700 1522230 1532094 1104256 1863278
35 I     Idaho                1353210 1438538 1739154 1541015 1122387 1772050
36 A     Alabama              1296530 1317711 1118631 1492583 1107408 1440134
37 M     Missouri             1221316 1858368 1773451 1573967 1374863 1486197
38 N     New Jersey           1605532 1141514 1613550 1181452 1541327 1156804
39 D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
40 D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
41 U     Utah                 1771096 1195861 1979395 1241662 1437456 1859416
42 M     Michigan             1295635 1149931 1601027 1340716 1729449 1567494
43 N     North Dakota         1618807 1510193 1876940 1443172 1425030 1868788
44 A     Alaska               1170302 1960378 1818085 1447852 1861639 1465841
45 L     Louisiana            1584734 1110625 1868456 1751920 1233709 1920301
46 N     Nebraska             1885081 1309769 1425527 1240465 1500594 1278272
47 V     Virginia             1134317 1163996 1891068 1853855 1708715 1197698
48 W     Washington           1977749 1687136 1199490 1163092 1334864 1621989
49 N     Nevada               1426117 1114500 1119707 1758830 1694526 1765826
50 A     Arizona              1742027 1968140 1377583 1782199 1102568 1109382
51 S     South Carolina       1631522 1803455 1425193 1458191 1538731 1825195
   Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1  1317983 1150783 1751389 1992996 1501879 1173694 1431705 1641866
2  1785986 1827503 1447457 1978374 1882532 1698698 1646508 1705322
3  1764457 1972730 1968730 1945524 1228529 1582249 1503156 1718072
4  1980167 1901394 1648755 1940943 1729177 1510119 1701650 1846238
5  1482786 1862351 1103794 1935687 1905378 1522129 1509171 1893515
6  1188104 1628980 1669295 1928238 1216675 1591896 1360959 1329341
7  1919423 1928416 1330509 1902816 1695126 1517184 1948108 1150882
8  1516621 1511460 1585465 1887714 1227303 1840898 1880804 1573117
9  1587602 1504455 1282142 1881814 1673668 1994022 1204029 1853858
10 1238174 1539322 1539603 1872519 1462137 1683127 1204344 1198791
11 1112765 1967225 1486246 1872327 1175819 1314343 1979529 1569566
12 1773090 1630325 1145473 1851245 1850111 1887157 1259353 1725470
13 1256746 1853142 1673831 1822933 1674707 1900523 1956742 1307678
14 1123567 1618583 1326369 1792600 1714960 1146278 1282790 1565924
15 1151409 1993136 1983569 1781016 1909119 1531212 1990412 1611730
16 1871645 1658551 1422021 1751422 1696729 1915435 1645465 1583516
17 1295877 1969163 1627262 1706080 1437088 1318546 1116792 1529233
18 1762936 1763211 1265642 1704297 1131298 1197576 1242623 1963313
19 1732098 1426216 1604531 1683687 1500089 1718837 1619033 1367705
20 1875146 1752387 1913275 1665877 1491604 1178355 1383978 1330736
21 1978904 1567651 1761048 1658538 1482203 1731917 1669749 1963337
22 1237704 1820856 1801430 1653384 1475715 1623388 1533494 1868612
23 1171870 1852424 1554782 1647245 1811156 1147488 1302834 1136443
24 1487315 1663809 1624509 1639670 1921845 1156536 1388461 1644607
25 1428291 1568049 1383227 1629132 1988270 1907777 1649668 1991232
26 1328133 1890633 1995304 1575533 1910216 1972021 1515366 1864553
27 1139551 1883976 1999102 1559924 1905760 1129794 1988394 1467614
28 1267737 1116168 1791535 1553750 1472258 1104893 1596452 1229085
29 1251742 1592690 1350619 1520064 1185225 1465705 1110394 1125903
30 1301848 1956681 1350895 1512894 1916616 1878271 1722762 1913350
31 1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389
32 1274168 1571032 1433835 1483292 1290329 1475344 1931500 1668232
33 1826406 1326460 1231739 1469785 1849041 1560887 1349173 1162164
34 1949478 1561528 1550433 1465812 1882929 1410249 1930090 1385528
35 1335481 1748608 1436809 1456340 1643855 1312561 1713718 1757171
36 1945229 1944173 1237582 1440756 1186741 1852841 1558906 1916661
37 1735099 1800620 1164202 1425363 1800052 1698105 1767835 1996005
38 1568034 1357418 1443718 1390010 1202326 1100990 1850165 1183568
39 1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183
40 1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508
41 1939284 1915865 1619186 1288285 1108281 1123353 1801019 1729273
42 1990431 1575185 1267626 1274673 1709853 1815596 1965196 1646634
43 1720352 1671468 1534571 1271132 1430978 1529024 1563898 1604118
44 1551826 1436541 1629616 1230866 1512804 1985302 1580394 1979143
45 1185085 1124853 1498662 1210385 1234234 1287663 1908602 1403857
46 1140598 1270585 1128711 1187207 1569665 1690920 1459243 1802211
47 1803330 1590043 1516758 1171686 1262342 1647032 1706707 1850394
48 1545621 1555554 1179331 1150089 1775787 1273834 1387428 1377341
49 1903270 1231480 1526066 1143343 1980195 1283813 1225348 1903804
50 1752886 1554330 1300521 1130709 1907284 1363279 1525866 1647724
51 1250499 1864685 1345102 1116203 1532332 1591735 1188417 1110655

## 2. Manipulate Variables

  <p> Nasledujúca tabuľka obsahuje základné funkcie na prácu s atribútmi/stĺpcami:</p>
  <table class="table table-bordered table-striped">
    <thead>
      <tr><th>Funkcia </th><th> Popis</th></tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-nowrap"><code>select(dataframe, variables)</code></td>
        <td> Výber požadovaných atribútov:
        <ul>
            <li><code>var1:var2</code>: výber atribútu <samp>var1</samp> až <samp>var2</samp></li>
            <li><code>-var</code>: odstránenie atribútu <samp>var</samp></li>
            <li><code>starts_with(" ")</code>:  výber atribútu začínajúci písmenom/písmenami</li>
            <li><code>end_with(" ")</code>: odtránenie atribútu s posledným písmenom/písmenami</li>
            <li><code>contains(" ")</code>: obsahuje doslovný reťazec </li>
            <li><code>everything()</code>: zmena poradia stĺpcov</li>
          </ul>  
        </td>
      </tr>
      <tr>
        <td class="text-nowrap"><code>select_if(dataframe, condition)</code></td>
        <td> Podmienený výber atribútov </td>
      </tr>
      <tr>
        <td class="text-nowrap"><code>mutate(dataframe, expression(s))</code></td>
        <td> Vytvorenie nového atribútu </td>
        </tr>
        <tr>
          <td class="text-nowrap"><code>mutate_all(dataframe, expression(s))</code></td>
          <td> Vytvorenie nových <samp>n</samp> atribútov z pôvodných <samp>n</samp> atribútov, aplikovaním vybraného výrazu  </td>
        </tr>
        <tr>
          <td class="text-nowrap"><code>mutate_if(dataframe, condition, expression(s))</code></td>
          <td> Podmienené vytvorenie nových atribútov </td>
        </tr>
        <tr>
            <td class="text-nowrap"><code>mutate_at(dataframe, variables, expression(s))</code></td>
            <td>Vytvorenie nových atribútov, aplikovaním výrazu na povodné atribúty</td>
        </tr>
        <tr>
          <td class="text-nowrap"><code>rename()</code></td>
          <td> Premenovanie atribútu</td>
      </tr>
    </tbody>
  </table>

### Príklady:

<b> <li> select variables / vyber atributov / stlpcov </li></b>

In [34]:
select(dataset, Index, State:Y2008)

   Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  A     Alabama              1296530 1317711 1118631 1492583 1107408 1440134
2  A     Alaska               1170302 1960378 1818085 1447852 1861639 1465841
3  A     Arizona              1742027 1968140 1377583 1782199 1102568 1109382
4  A     Arkansas             1485531 1994927 1119299 1947979 1669191 1801213
5  C     California           1685349 1675807 1889570 1480280 1735069 1812546
6  C     Colorado             1343824 1878473 1886149 1236697 1871471 1814218
7  C     Connecticut          1610512 1232844 1181949 1518933 1841266 1976976
8  D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
9  D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
10 F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
11 G     Georgia              1929009 1541565 1810773 1779091 1326846 1223770
12 H     Hawaii               1461570 1200280 1213993 1245931 1459383 1430465
13 I     Idaho                1353210 1438538 1739154 1541015 1122387 1772050
14 I     Illinois             1508356 1527440 1493029 1261353 1540274 1747614
15 I     Indiana              1776918 1734104 1269927 1204117 1848073 1129546
16 I     Iowa                 1499269 1444576 1576367 1388924 1554813 1452911
17 K     Kansas               1509054 1290700 1522230 1532094 1104256 1863278
18 K     Kentucky             1813878 1448846 1800760 1250524 1137913 1911227
19 L     Louisiana            1584734 1110625 1868456 1751920 1233709 1920301
20 M     Maine                1582720 1678622 1208496 1912040 1438549 1330014
21 M     Maryland             1579713 1404700 1849798 1397738 1310270 1789128
22 M     Massachusetts        1647582 1686259 1620601 1777250 1531641 1380529
23 M     Michigan             1295635 1149931 1601027 1340716 1729449 1567494
24 M     Minnesota            1729921 1675204 1903907 1561839 1985692 1148621
25 M     Mississippi          1983285 1292558 1631325 1943311 1354579 1731643
26 M     Missouri             1221316 1858368 1773451 1573967 1374863 1486197
27 M     Montana              1877154 1540099 1332722 1273327 1625721 1983568
28 N     Nebraska             1885081 1309769 1425527 1240465 1500594 1278272
29 N     Nevada               1426117 1114500 1119707 1758830 1694526 1765826
30 N     New Hampshire        1419776 1854370 1195119 1990062 1645430 1286967
31 N     New Jersey           1605532 1141514 1613550 1181452 1541327 1156804
32 N     New Mexico           1819239 1226057 1935991 1124400 1723493 1475985
33 N     New York             1395149 1611371 1170675 1446810 1426941 1463171
34 N     North Carolina       1616742 1292223 1482792 1532347 1158716 1827420
35 N     North Dakota         1618807 1510193 1876940 1443172 1425030 1868788
36 O     Ohio                 1802132 1648498 1441386 1670280 1534888 1314824
37 O     Oklahoma             1173918 1334639 1663622 1798714 1312574 1708245
38 O     Oregon               1794912 1726665 1805445 1133510 1502242 1419251
39 P     Pennsylvania         1320191 1446723 1218591 1122030 1971479 1563062
40 R     Rhode Island         1501744 1942942 1266657 1961923 1835983 1234040
41 S     South Carolina       1631522 1803455 1425193 1458191 1538731 1825195
42 S     South Dakota         1159037 1150689 1660148 1417141 1418586 1279134
43 T     Tennessee            1811867 1485909 1974179 1157059 1786132 1399191
44 T     Texas                1520591 1310777 1957713 1907326 1873544 1655483
45 U     Utah                 1771096 1195861 1979395 1241662 1437456 1859416
46 V     Vermont              1146902 1832249 1492704 1579265 1332048 1563537
47 V     Virginia             1134317 1163996 1891068 1853855 1708715 1197698
48 W     Washington           1977749 1687136 1199490 1163092 1334864 1621989
49 W     West Virginia        1677347 1380662 1176100 1888948 1922085 1740826
50 W     Wisconsin            1788920 1518578 1289663 1436888 1251678 1721874
51 W     Wyoming              1775190 1498098 1198212 1881688 1750527 1523124
   Y2008
1  1945229
2  1551826
3  1752886
4  1188104
5  1487315
6  1875146
7  1764457
8  1762096
9  1193245
10 1756185
11 1773090
12 1919423
13 1335481
14 1871645
15 1139551
16 1317983
17 1949478
18 1301848
19 1185085
20 1295877
21 1112765
22 1978904
23 1990431
24 1328133
25 1428291
26 1735099
27 1251742
28 1140598
29 1903270
30 1762936
31 1568034
32 1237704
33 1732098
34 1267737
35 1720352
36 1516621
37 1256746
38 1482786
39 1274168
40 1151409
41 1250499
42 1171870
43 1826406
44 1785986
45 1939284
46 1123567
47 1803330
48 1545621
49 1238174
50 1980167
51 1587602

In [35]:
select(dataset, -Index, -State)

   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008   Y2009   Y2010
1  1296530 1317711 1118631 1492583 1107408 1440134 1945229 1944173 1237582
2  1170302 1960378 1818085 1447852 1861639 1465841 1551826 1436541 1629616
3  1742027 1968140 1377583 1782199 1102568 1109382 1752886 1554330 1300521
4  1485531 1994927 1119299 1947979 1669191 1801213 1188104 1628980 1669295
5  1685349 1675807 1889570 1480280 1735069 1812546 1487315 1663809 1624509
6  1343824 1878473 1886149 1236697 1871471 1814218 1875146 1752387 1913275
7  1610512 1232844 1181949 1518933 1841266 1976976 1764457 1972730 1968730
8  1330403 1268673 1706751 1403759 1441351 1300836 1762096 1553585 1370984
9  1111437 1993741 1374643 1827949 1803852 1595981 1193245 1739748 1707823
10 1964626 1468852 1419738 1362787 1339608 1278550 1756185 1818438 1198403
11 1929009 1541565 1810773 1779091 1326846 1223770 1773090 1630325 1145473
12 1461570 1200280 1213993 1245931 1459383 1430465 1919423 1928416 1330509
13 1353210 1438538 1739154 1541015 1122387 1772050 1335481 1748608 1436809
14 1508356 1527440 1493029 1261353 1540274 1747614 1871645 1658551 1422021
15 1776918 1734104 1269927 1204117 1848073 1129546 1139551 1883976 1999102
16 1499269 1444576 1576367 1388924 1554813 1452911 1317983 1150783 1751389
17 1509054 1290700 1522230 1532094 1104256 1863278 1949478 1561528 1550433
18 1813878 1448846 1800760 1250524 1137913 1911227 1301848 1956681 1350895
19 1584734 1110625 1868456 1751920 1233709 1920301 1185085 1124853 1498662
20 1582720 1678622 1208496 1912040 1438549 1330014 1295877 1969163 1627262
21 1579713 1404700 1849798 1397738 1310270 1789128 1112765 1967225 1486246
22 1647582 1686259 1620601 1777250 1531641 1380529 1978904 1567651 1761048
23 1295635 1149931 1601027 1340716 1729449 1567494 1990431 1575185 1267626
24 1729921 1675204 1903907 1561839 1985692 1148621 1328133 1890633 1995304
25 1983285 1292558 1631325 1943311 1354579 1731643 1428291 1568049 1383227
26 1221316 1858368 1773451 1573967 1374863 1486197 1735099 1800620 1164202
27 1877154 1540099 1332722 1273327 1625721 1983568 1251742 1592690 1350619
28 1885081 1309769 1425527 1240465 1500594 1278272 1140598 1270585 1128711
29 1426117 1114500 1119707 1758830 1694526 1765826 1903270 1231480 1526066
30 1419776 1854370 1195119 1990062 1645430 1286967 1762936 1763211 1265642
31 1605532 1141514 1613550 1181452 1541327 1156804 1568034 1357418 1443718
32 1819239 1226057 1935991 1124400 1723493 1475985 1237704 1820856 1801430
33 1395149 1611371 1170675 1446810 1426941 1463171 1732098 1426216 1604531
34 1616742 1292223 1482792 1532347 1158716 1827420 1267737 1116168 1791535
35 1618807 1510193 1876940 1443172 1425030 1868788 1720352 1671468 1534571
36 1802132 1648498 1441386 1670280 1534888 1314824 1516621 1511460 1585465
37 1173918 1334639 1663622 1798714 1312574 1708245 1256746 1853142 1673831
38 1794912 1726665 1805445 1133510 1502242 1419251 1482786 1862351 1103794
39 1320191 1446723 1218591 1122030 1971479 1563062 1274168 1571032 1433835
40 1501744 1942942 1266657 1961923 1835983 1234040 1151409 1993136 1983569
41 1631522 1803455 1425193 1458191 1538731 1825195 1250499 1864685 1345102
42 1159037 1150689 1660148 1417141 1418586 1279134 1171870 1852424 1554782
43 1811867 1485909 1974179 1157059 1786132 1399191 1826406 1326460 1231739
44 1520591 1310777 1957713 1907326 1873544 1655483 1785986 1827503 1447457
45 1771096 1195861 1979395 1241662 1437456 1859416 1939284 1915865 1619186
46 1146902 1832249 1492704 1579265 1332048 1563537 1123567 1618583 1326369
47 1134317 1163996 1891068 1853855 1708715 1197698 1803330 1590043 1516758
48 1977749 1687136 1199490 1163092 1334864 1621989 1545621 1555554 1179331
49 1677347 1380662 1176100 1888948 1922085 1740826 1238174 1539322 1539603
50 1788920 1518578 1289663 1436888 1251678 1721874 1980167 1901394 1648755
51 1775190 1498098 1198212 1881688 1750527 1523124 1587602 1504455 1282142
   Y2011   Y2012   Y2013   Y2014   Y2015
1  1440756 1186741 1852841 1558906 1916661
2  1230866 1512804 1985302 1580394 1979143
3  1130709 1907284 1363279 1525866 1647724
4  1928238 1216675 1591896 1360959 1329341
5  1639670 1921845 1156536 1388461 1644607
6  1665877 1491604 1178355 1383978 1330736
7  1945524 1228529 1582249 1503156 1718072
8  1318669 1984027 1671279 1803169 1627508
9  1353449 1979708 1912654 1782169 1410183
10 1497051 1131928 1107448 1407784 1170389
11 1851245 1850111 1887157 1259353 1725470
12 1902816 1695126 1517184 1948108 1150882
13 1456340 1643855 1312561 1713718 1757171
14 1751422 1696729 1915435 1645465 1583516
15 1559924 1905760 1129794 1988394 1467614
16 1992996 1501879 1173694 1431705 1641866
17 1465812 1882929 1410249 1930090 1385528
18 1512894 1916616 1878271 1722762 1913350
19 1210385 1234234 1287663 1908602 1403857
20 1706080 1437088 1318546 1116792 1529233
21 1872327 1175819 1314343 1979529 1569566
22 1658538 1482203 1731917 1669749 1963337
23 1274673 1709853 1815596 1965196 1646634
24 1575533 1910216 1972021 1515366 1864553
25 1629132 1988270 1907777 1649668 1991232
26 1425363 1800052 1698105 1767835 1996005
27 1520064 1185225 1465705 1110394 1125903
28 1187207 1569665 1690920 1459243 1802211
29 1143343 1980195 1283813 1225348 1903804
30 1704297 1131298 1197576 1242623 1963313
31 1390010 1202326 1100990 1850165 1183568
32 1653384 1475715 1623388 1533494 1868612
33 1683687 1500089 1718837 1619033 1367705
34 1553750 1472258 1104893 1596452 1229085
35 1271132 1430978 1529024 1563898 1604118
36 1887714 1227303 1840898 1880804 1573117
37 1822933 1674707 1900523 1956742 1307678
38 1935687 1905378 1522129 1509171 1893515
39 1483292 1290329 1475344 1931500 1668232
40 1781016 1909119 1531212 1990412 1611730
41 1116203 1532332 1591735 1188417 1110655
42 1647245 1811156 1147488 1302834 1136443
43 1469785 1849041 1560887 1349173 1162164
44 1978374 1882532 1698698 1646508 1705322
45 1288285 1108281 1123353 1801019 1729273
46 1792600 1714960 1146278 1282790 1565924
47 1171686 1262342 1647032 1706707 1850394
48 1150089 1775787 1273834 1387428 1377341
49 1872519 1462137 1683127 1204344 1198791
50 1940943 1729177 1510119 1701650 1846238
51 1881814 1673668 1994022 1204029 1853858

In [36]:
select(dataset, starts_with("Y"))

   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008   Y2009   Y2010
1  1296530 1317711 1118631 1492583 1107408 1440134 1945229 1944173 1237582
2  1170302 1960378 1818085 1447852 1861639 1465841 1551826 1436541 1629616
3  1742027 1968140 1377583 1782199 1102568 1109382 1752886 1554330 1300521
4  1485531 1994927 1119299 1947979 1669191 1801213 1188104 1628980 1669295
5  1685349 1675807 1889570 1480280 1735069 1812546 1487315 1663809 1624509
6  1343824 1878473 1886149 1236697 1871471 1814218 1875146 1752387 1913275
7  1610512 1232844 1181949 1518933 1841266 1976976 1764457 1972730 1968730
8  1330403 1268673 1706751 1403759 1441351 1300836 1762096 1553585 1370984
9  1111437 1993741 1374643 1827949 1803852 1595981 1193245 1739748 1707823
10 1964626 1468852 1419738 1362787 1339608 1278550 1756185 1818438 1198403
11 1929009 1541565 1810773 1779091 1326846 1223770 1773090 1630325 1145473
12 1461570 1200280 1213993 1245931 1459383 1430465 1919423 1928416 1330509
13 1353210 1438538 1739154 1541015 1122387 1772050 1335481 1748608 1436809
14 1508356 1527440 1493029 1261353 1540274 1747614 1871645 1658551 1422021
15 1776918 1734104 1269927 1204117 1848073 1129546 1139551 1883976 1999102
16 1499269 1444576 1576367 1388924 1554813 1452911 1317983 1150783 1751389
17 1509054 1290700 1522230 1532094 1104256 1863278 1949478 1561528 1550433
18 1813878 1448846 1800760 1250524 1137913 1911227 1301848 1956681 1350895
19 1584734 1110625 1868456 1751920 1233709 1920301 1185085 1124853 1498662
20 1582720 1678622 1208496 1912040 1438549 1330014 1295877 1969163 1627262
21 1579713 1404700 1849798 1397738 1310270 1789128 1112765 1967225 1486246
22 1647582 1686259 1620601 1777250 1531641 1380529 1978904 1567651 1761048
23 1295635 1149931 1601027 1340716 1729449 1567494 1990431 1575185 1267626
24 1729921 1675204 1903907 1561839 1985692 1148621 1328133 1890633 1995304
25 1983285 1292558 1631325 1943311 1354579 1731643 1428291 1568049 1383227
26 1221316 1858368 1773451 1573967 1374863 1486197 1735099 1800620 1164202
27 1877154 1540099 1332722 1273327 1625721 1983568 1251742 1592690 1350619
28 1885081 1309769 1425527 1240465 1500594 1278272 1140598 1270585 1128711
29 1426117 1114500 1119707 1758830 1694526 1765826 1903270 1231480 1526066
30 1419776 1854370 1195119 1990062 1645430 1286967 1762936 1763211 1265642
31 1605532 1141514 1613550 1181452 1541327 1156804 1568034 1357418 1443718
32 1819239 1226057 1935991 1124400 1723493 1475985 1237704 1820856 1801430
33 1395149 1611371 1170675 1446810 1426941 1463171 1732098 1426216 1604531
34 1616742 1292223 1482792 1532347 1158716 1827420 1267737 1116168 1791535
35 1618807 1510193 1876940 1443172 1425030 1868788 1720352 1671468 1534571
36 1802132 1648498 1441386 1670280 1534888 1314824 1516621 1511460 1585465
37 1173918 1334639 1663622 1798714 1312574 1708245 1256746 1853142 1673831
38 1794912 1726665 1805445 1133510 1502242 1419251 1482786 1862351 1103794
39 1320191 1446723 1218591 1122030 1971479 1563062 1274168 1571032 1433835
40 1501744 1942942 1266657 1961923 1835983 1234040 1151409 1993136 1983569
41 1631522 1803455 1425193 1458191 1538731 1825195 1250499 1864685 1345102
42 1159037 1150689 1660148 1417141 1418586 1279134 1171870 1852424 1554782
43 1811867 1485909 1974179 1157059 1786132 1399191 1826406 1326460 1231739
44 1520591 1310777 1957713 1907326 1873544 1655483 1785986 1827503 1447457
45 1771096 1195861 1979395 1241662 1437456 1859416 1939284 1915865 1619186
46 1146902 1832249 1492704 1579265 1332048 1563537 1123567 1618583 1326369
47 1134317 1163996 1891068 1853855 1708715 1197698 1803330 1590043 1516758
48 1977749 1687136 1199490 1163092 1334864 1621989 1545621 1555554 1179331
49 1677347 1380662 1176100 1888948 1922085 1740826 1238174 1539322 1539603
50 1788920 1518578 1289663 1436888 1251678 1721874 1980167 1901394 1648755
51 1775190 1498098 1198212 1881688 1750527 1523124 1587602 1504455 1282142
   Y2011   Y2012   Y2013   Y2014   Y2015
1  1440756 1186741 1852841 1558906 1916661
2  1230866 1512804 1985302 1580394 1979143
3  1130709 1907284 1363279 1525866 1647724
4  1928238 1216675 1591896 1360959 1329341
5  1639670 1921845 1156536 1388461 1644607
6  1665877 1491604 1178355 1383978 1330736
7  1945524 1228529 1582249 1503156 1718072
8  1318669 1984027 1671279 1803169 1627508
9  1353449 1979708 1912654 1782169 1410183
10 1497051 1131928 1107448 1407784 1170389
11 1851245 1850111 1887157 1259353 1725470
12 1902816 1695126 1517184 1948108 1150882
13 1456340 1643855 1312561 1713718 1757171
14 1751422 1696729 1915435 1645465 1583516
15 1559924 1905760 1129794 1988394 1467614
16 1992996 1501879 1173694 1431705 1641866
17 1465812 1882929 1410249 1930090 1385528
18 1512894 1916616 1878271 1722762 1913350
19 1210385 1234234 1287663 1908602 1403857
20 1706080 1437088 1318546 1116792 1529233
21 1872327 1175819 1314343 1979529 1569566
22 1658538 1482203 1731917 1669749 1963337
23 1274673 1709853 1815596 1965196 1646634
24 1575533 1910216 1972021 1515366 1864553
25 1629132 1988270 1907777 1649668 1991232
26 1425363 1800052 1698105 1767835 1996005
27 1520064 1185225 1465705 1110394 1125903
28 1187207 1569665 1690920 1459243 1802211
29 1143343 1980195 1283813 1225348 1903804
30 1704297 1131298 1197576 1242623 1963313
31 1390010 1202326 1100990 1850165 1183568
32 1653384 1475715 1623388 1533494 1868612
33 1683687 1500089 1718837 1619033 1367705
34 1553750 1472258 1104893 1596452 1229085
35 1271132 1430978 1529024 1563898 1604118
36 1887714 1227303 1840898 1880804 1573117
37 1822933 1674707 1900523 1956742 1307678
38 1935687 1905378 1522129 1509171 1893515
39 1483292 1290329 1475344 1931500 1668232
40 1781016 1909119 1531212 1990412 1611730
41 1116203 1532332 1591735 1188417 1110655
42 1647245 1811156 1147488 1302834 1136443
43 1469785 1849041 1560887 1349173 1162164
44 1978374 1882532 1698698 1646508 1705322
45 1288285 1108281 1123353 1801019 1729273
46 1792600 1714960 1146278 1282790 1565924
47 1171686 1262342 1647032 1706707 1850394
48 1150089 1775787 1273834 1387428 1377341
49 1872519 1462137 1683127 1204344 1198791
50 1940943 1729177 1510119 1701650 1846238
51 1881814 1673668 1994022 1204029 1853858

In [37]:
select(dataset, -starts_with ("Y"))

   Index State
1  A     Alabama
2  A     Alaska
3  A     Arizona
4  A     Arkansas
5  C     California
6  C     Colorado
7  C     Connecticut
8  D     Delaware
9  D     District of Columbia
10 F     Florida
11 G     Georgia
12 H     Hawaii
13 I     Idaho
14 I     Illinois
15 I     Indiana
16 I     Iowa
17 K     Kansas
18 K     Kentucky
19 L     Louisiana
20 M     Maine
21 M     Maryland
22 M     Massachusetts
23 M     Michigan
24 M     Minnesota
25 M     Mississippi
26 M     Missouri
27 M     Montana
28 N     Nebraska
29 N     Nevada
30 N     New Hampshire
31 N     New Jersey
32 N     New Mexico
33 N     New York
34 N     North Carolina
35 N     North Dakota
36 O     Ohio
37 O     Oklahoma
38 O     Oregon
39 P     Pennsylvania
40 R     Rhode Island
41 S     South Carolina
42 S     South Dakota
43 T     Tennessee
44 T     Texas
45 U     Utah
46 V     Vermont
47 V     Virginia
48 W     Washington
49 W     West Virginia
50 W     Wisconsin
51 W     Wyoming

In [38]:
select(dataset, contains("St"))

   State
1  Alabama
2  Alaska
3  Arizona
4  Arkansas
5  California
6  Colorado
7  Connecticut
8  Delaware
9  District of Columbia
10 Florida
11 Georgia
12 Hawaii
13 Idaho
14 Illinois
15 Indiana
16 Iowa
17 Kansas
18 Kentucky
19 Louisiana
20 Maine
21 Maryland
22 Massachusetts
23 Michigan
24 Minnesota
25 Mississippi
26 Missouri
27 Montana
28 Nebraska
29 Nevada
30 New Hampshire
31 New Jersey
32 New Mexico
33 New York
34 North Carolina
35 North Dakota
36 Ohio
37 Oklahoma
38 Oregon
39 Pennsylvania
40 Rhode Island
41 South Carolina
42 South Dakota
43 Tennessee
44 Texas
45 Utah
46 Vermont
47 Virginia
48 Washington
49 West Virginia
50 Wisconsin
51 Wyoming

In [39]:
select(dataset, State, everything())

   State                Index Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  Alabama              A     1296530 1317711 1118631 1492583 1107408 1440134
2  Alaska               A     1170302 1960378 1818085 1447852 1861639 1465841
3  Arizona              A     1742027 1968140 1377583 1782199 1102568 1109382
4  Arkansas             A     1485531 1994927 1119299 1947979 1669191 1801213
5  California           C     1685349 1675807 1889570 1480280 1735069 1812546
6  Colorado             C     1343824 1878473 1886149 1236697 1871471 1814218
7  Connecticut          C     1610512 1232844 1181949 1518933 1841266 1976976
8  Delaware             D     1330403 1268673 1706751 1403759 1441351 1300836
9  District of Columbia D     1111437 1993741 1374643 1827949 1803852 1595981
10 Florida              F     1964626 1468852 1419738 1362787 1339608 1278550
11 Georgia              G     1929009 1541565 1810773 1779091 1326846 1223770
12 Hawaii               H     1461570 1200280 1213993 1245931 1459383 1430465
13 Idaho                I     1353210 1438538 1739154 1541015 1122387 1772050
14 Illinois             I     1508356 1527440 1493029 1261353 1540274 1747614
15 Indiana              I     1776918 1734104 1269927 1204117 1848073 1129546
16 Iowa                 I     1499269 1444576 1576367 1388924 1554813 1452911
17 Kansas               K     1509054 1290700 1522230 1532094 1104256 1863278
18 Kentucky             K     1813878 1448846 1800760 1250524 1137913 1911227
19 Louisiana            L     1584734 1110625 1868456 1751920 1233709 1920301
20 Maine                M     1582720 1678622 1208496 1912040 1438549 1330014
21 Maryland             M     1579713 1404700 1849798 1397738 1310270 1789128
22 Massachusetts        M     1647582 1686259 1620601 1777250 1531641 1380529
23 Michigan             M     1295635 1149931 1601027 1340716 1729449 1567494
24 Minnesota            M     1729921 1675204 1903907 1561839 1985692 1148621
25 Mississippi          M     1983285 1292558 1631325 1943311 1354579 1731643
26 Missouri             M     1221316 1858368 1773451 1573967 1374863 1486197
27 Montana              M     1877154 1540099 1332722 1273327 1625721 1983568
28 Nebraska             N     1885081 1309769 1425527 1240465 1500594 1278272
29 Nevada               N     1426117 1114500 1119707 1758830 1694526 1765826
30 New Hampshire        N     1419776 1854370 1195119 1990062 1645430 1286967
31 New Jersey           N     1605532 1141514 1613550 1181452 1541327 1156804
32 New Mexico           N     1819239 1226057 1935991 1124400 1723493 1475985
33 New York             N     1395149 1611371 1170675 1446810 1426941 1463171
34 North Carolina       N     1616742 1292223 1482792 1532347 1158716 1827420
35 North Dakota         N     1618807 1510193 1876940 1443172 1425030 1868788
36 Ohio                 O     1802132 1648498 1441386 1670280 1534888 1314824
37 Oklahoma             O     1173918 1334639 1663622 1798714 1312574 1708245
38 Oregon               O     1794912 1726665 1805445 1133510 1502242 1419251
39 Pennsylvania         P     1320191 1446723 1218591 1122030 1971479 1563062
40 Rhode Island         R     1501744 1942942 1266657 1961923 1835983 1234040
41 South Carolina       S     1631522 1803455 1425193 1458191 1538731 1825195
42 South Dakota         S     1159037 1150689 1660148 1417141 1418586 1279134
43 Tennessee            T     1811867 1485909 1974179 1157059 1786132 1399191
44 Texas                T     1520591 1310777 1957713 1907326 1873544 1655483
45 Utah                 U     1771096 1195861 1979395 1241662 1437456 1859416
46 Vermont              V     1146902 1832249 1492704 1579265 1332048 1563537
47 Virginia             V     1134317 1163996 1891068 1853855 1708715 1197698
48 Washington           W     1977749 1687136 1199490 1163092 1334864 1621989
49 West Virginia        W     1677347 1380662 1176100 1888948 1922085 1740826
50 Wisconsin            W     1788920 1518578 1289663 1436888 1251678 1721874
51 Wyoming              W     1775190 1498098 1198212 1881688 1750527 1523124
   Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1  1945229 1944173 1237582 1440756 1186741 1852841 1558906 1916661
2  1551826 1436541 1629616 1230866 1512804 1985302 1580394 1979143
3  1752886 1554330 1300521 1130709 1907284 1363279 1525866 1647724
4  1188104 1628980 1669295 1928238 1216675 1591896 1360959 1329341
5  1487315 1663809 1624509 1639670 1921845 1156536 1388461 1644607
6  1875146 1752387 1913275 1665877 1491604 1178355 1383978 1330736
7  1764457 1972730 1968730 1945524 1228529 1582249 1503156 1718072
8  1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508
9  1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183
10 1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389
11 1773090 1630325 1145473 1851245 1850111 1887157 1259353 1725470
12 1919423 1928416 1330509 1902816 1695126 1517184 1948108 1150882
13 1335481 1748608 1436809 1456340 1643855 1312561 1713718 1757171
14 1871645 1658551 1422021 1751422 1696729 1915435 1645465 1583516
15 1139551 1883976 1999102 1559924 1905760 1129794 1988394 1467614
16 1317983 1150783 1751389 1992996 1501879 1173694 1431705 1641866
17 1949478 1561528 1550433 1465812 1882929 1410249 1930090 1385528
18 1301848 1956681 1350895 1512894 1916616 1878271 1722762 1913350
19 1185085 1124853 1498662 1210385 1234234 1287663 1908602 1403857
20 1295877 1969163 1627262 1706080 1437088 1318546 1116792 1529233
21 1112765 1967225 1486246 1872327 1175819 1314343 1979529 1569566
22 1978904 1567651 1761048 1658538 1482203 1731917 1669749 1963337
23 1990431 1575185 1267626 1274673 1709853 1815596 1965196 1646634
24 1328133 1890633 1995304 1575533 1910216 1972021 1515366 1864553
25 1428291 1568049 1383227 1629132 1988270 1907777 1649668 1991232
26 1735099 1800620 1164202 1425363 1800052 1698105 1767835 1996005
27 1251742 1592690 1350619 1520064 1185225 1465705 1110394 1125903
28 1140598 1270585 1128711 1187207 1569665 1690920 1459243 1802211
29 1903270 1231480 1526066 1143343 1980195 1283813 1225348 1903804
30 1762936 1763211 1265642 1704297 1131298 1197576 1242623 1963313
31 1568034 1357418 1443718 1390010 1202326 1100990 1850165 1183568
32 1237704 1820856 1801430 1653384 1475715 1623388 1533494 1868612
33 1732098 1426216 1604531 1683687 1500089 1718837 1619033 1367705
34 1267737 1116168 1791535 1553750 1472258 1104893 1596452 1229085
35 1720352 1671468 1534571 1271132 1430978 1529024 1563898 1604118
36 1516621 1511460 1585465 1887714 1227303 1840898 1880804 1573117
37 1256746 1853142 1673831 1822933 1674707 1900523 1956742 1307678
38 1482786 1862351 1103794 1935687 1905378 1522129 1509171 1893515
39 1274168 1571032 1433835 1483292 1290329 1475344 1931500 1668232
40 1151409 1993136 1983569 1781016 1909119 1531212 1990412 1611730
41 1250499 1864685 1345102 1116203 1532332 1591735 1188417 1110655
42 1171870 1852424 1554782 1647245 1811156 1147488 1302834 1136443
43 1826406 1326460 1231739 1469785 1849041 1560887 1349173 1162164
44 1785986 1827503 1447457 1978374 1882532 1698698 1646508 1705322
45 1939284 1915865 1619186 1288285 1108281 1123353 1801019 1729273
46 1123567 1618583 1326369 1792600 1714960 1146278 1282790 1565924
47 1803330 1590043 1516758 1171686 1262342 1647032 1706707 1850394
48 1545621 1555554 1179331 1150089 1775787 1273834 1387428 1377341
49 1238174 1539322 1539603 1872519 1462137 1683127 1204344 1198791
50 1980167 1901394 1648755 1940943 1729177 1510119 1701650 1846238
51 1587602 1504455 1282142 1881814 1673668 1994022 1204029 1853858

<b> <li> select_if / podmieneny vyber </li></b>

In [40]:
select_if(dataset, is.numeric)

   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008   Y2009   Y2010
1  1296530 1317711 1118631 1492583 1107408 1440134 1945229 1944173 1237582
2  1170302 1960378 1818085 1447852 1861639 1465841 1551826 1436541 1629616
3  1742027 1968140 1377583 1782199 1102568 1109382 1752886 1554330 1300521
4  1485531 1994927 1119299 1947979 1669191 1801213 1188104 1628980 1669295
5  1685349 1675807 1889570 1480280 1735069 1812546 1487315 1663809 1624509
6  1343824 1878473 1886149 1236697 1871471 1814218 1875146 1752387 1913275
7  1610512 1232844 1181949 1518933 1841266 1976976 1764457 1972730 1968730
8  1330403 1268673 1706751 1403759 1441351 1300836 1762096 1553585 1370984
9  1111437 1993741 1374643 1827949 1803852 1595981 1193245 1739748 1707823
10 1964626 1468852 1419738 1362787 1339608 1278550 1756185 1818438 1198403
11 1929009 1541565 1810773 1779091 1326846 1223770 1773090 1630325 1145473
12 1461570 1200280 1213993 1245931 1459383 1430465 1919423 1928416 1330509
13 1353210 1438538 1739154 1541015 1122387 1772050 1335481 1748608 1436809
14 1508356 1527440 1493029 1261353 1540274 1747614 1871645 1658551 1422021
15 1776918 1734104 1269927 1204117 1848073 1129546 1139551 1883976 1999102
16 1499269 1444576 1576367 1388924 1554813 1452911 1317983 1150783 1751389
17 1509054 1290700 1522230 1532094 1104256 1863278 1949478 1561528 1550433
18 1813878 1448846 1800760 1250524 1137913 1911227 1301848 1956681 1350895
19 1584734 1110625 1868456 1751920 1233709 1920301 1185085 1124853 1498662
20 1582720 1678622 1208496 1912040 1438549 1330014 1295877 1969163 1627262
21 1579713 1404700 1849798 1397738 1310270 1789128 1112765 1967225 1486246
22 1647582 1686259 1620601 1777250 1531641 1380529 1978904 1567651 1761048
23 1295635 1149931 1601027 1340716 1729449 1567494 1990431 1575185 1267626
24 1729921 1675204 1903907 1561839 1985692 1148621 1328133 1890633 1995304
25 1983285 1292558 1631325 1943311 1354579 1731643 1428291 1568049 1383227
26 1221316 1858368 1773451 1573967 1374863 1486197 1735099 1800620 1164202
27 1877154 1540099 1332722 1273327 1625721 1983568 1251742 1592690 1350619
28 1885081 1309769 1425527 1240465 1500594 1278272 1140598 1270585 1128711
29 1426117 1114500 1119707 1758830 1694526 1765826 1903270 1231480 1526066
30 1419776 1854370 1195119 1990062 1645430 1286967 1762936 1763211 1265642
31 1605532 1141514 1613550 1181452 1541327 1156804 1568034 1357418 1443718
32 1819239 1226057 1935991 1124400 1723493 1475985 1237704 1820856 1801430
33 1395149 1611371 1170675 1446810 1426941 1463171 1732098 1426216 1604531
34 1616742 1292223 1482792 1532347 1158716 1827420 1267737 1116168 1791535
35 1618807 1510193 1876940 1443172 1425030 1868788 1720352 1671468 1534571
36 1802132 1648498 1441386 1670280 1534888 1314824 1516621 1511460 1585465
37 1173918 1334639 1663622 1798714 1312574 1708245 1256746 1853142 1673831
38 1794912 1726665 1805445 1133510 1502242 1419251 1482786 1862351 1103794
39 1320191 1446723 1218591 1122030 1971479 1563062 1274168 1571032 1433835
40 1501744 1942942 1266657 1961923 1835983 1234040 1151409 1993136 1983569
41 1631522 1803455 1425193 1458191 1538731 1825195 1250499 1864685 1345102
42 1159037 1150689 1660148 1417141 1418586 1279134 1171870 1852424 1554782
43 1811867 1485909 1974179 1157059 1786132 1399191 1826406 1326460 1231739
44 1520591 1310777 1957713 1907326 1873544 1655483 1785986 1827503 1447457
45 1771096 1195861 1979395 1241662 1437456 1859416 1939284 1915865 1619186
46 1146902 1832249 1492704 1579265 1332048 1563537 1123567 1618583 1326369
47 1134317 1163996 1891068 1853855 1708715 1197698 1803330 1590043 1516758
48 1977749 1687136 1199490 1163092 1334864 1621989 1545621 1555554 1179331
49 1677347 1380662 1176100 1888948 1922085 1740826 1238174 1539322 1539603
50 1788920 1518578 1289663 1436888 1251678 1721874 1980167 1901394 1648755
51 1775190 1498098 1198212 1881688 1750527 1523124 1587602 1504455 1282142
   Y2011   Y2012   Y2013   Y2014   Y2015
1  1440756 1186741 1852841 1558906 1916661
2  1230866 1512804 1985302 1580394 1979143
3  1130709 1907284 1363279 1525866 1647724
4  1928238 1216675 1591896 1360959 1329341
5  1639670 1921845 1156536 1388461 1644607
6  1665877 1491604 1178355 1383978 1330736
7  1945524 1228529 1582249 1503156 1718072
8  1318669 1984027 1671279 1803169 1627508
9  1353449 1979708 1912654 1782169 1410183
10 1497051 1131928 1107448 1407784 1170389
11 1851245 1850111 1887157 1259353 1725470
12 1902816 1695126 1517184 1948108 1150882
13 1456340 1643855 1312561 1713718 1757171
14 1751422 1696729 1915435 1645465 1583516
15 1559924 1905760 1129794 1988394 1467614
16 1992996 1501879 1173694 1431705 1641866
17 1465812 1882929 1410249 1930090 1385528
18 1512894 1916616 1878271 1722762 1913350
19 1210385 1234234 1287663 1908602 1403857
20 1706080 1437088 1318546 1116792 1529233
21 1872327 1175819 1314343 1979529 1569566
22 1658538 1482203 1731917 1669749 1963337
23 1274673 1709853 1815596 1965196 1646634
24 1575533 1910216 1972021 1515366 1864553
25 1629132 1988270 1907777 1649668 1991232
26 1425363 1800052 1698105 1767835 1996005
27 1520064 1185225 1465705 1110394 1125903
28 1187207 1569665 1690920 1459243 1802211
29 1143343 1980195 1283813 1225348 1903804
30 1704297 1131298 1197576 1242623 1963313
31 1390010 1202326 1100990 1850165 1183568
32 1653384 1475715 1623388 1533494 1868612
33 1683687 1500089 1718837 1619033 1367705
34 1553750 1472258 1104893 1596452 1229085
35 1271132 1430978 1529024 1563898 1604118
36 1887714 1227303 1840898 1880804 1573117
37 1822933 1674707 1900523 1956742 1307678
38 1935687 1905378 1522129 1509171 1893515
39 1483292 1290329 1475344 1931500 1668232
40 1781016 1909119 1531212 1990412 1611730
41 1116203 1532332 1591735 1188417 1110655
42 1647245 1811156 1147488 1302834 1136443
43 1469785 1849041 1560887 1349173 1162164
44 1978374 1882532 1698698 1646508 1705322
45 1288285 1108281 1123353 1801019 1729273
46 1792600 1714960 1146278 1282790 1565924
47 1171686 1262342 1647032 1706707 1850394
48 1150089 1775787 1273834 1387428 1377341
49 1872519 1462137 1683127 1204344 1198791
50 1940943 1729177 1510119 1701650 1846238
51 1881814 1673668 1994022 1204029 1853858

In [41]:
select_if(dataset, is.factor)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51

<b> <li> mutate function / create a new variable </li></b>

In [42]:
mutate(dataset, new=Y2015/Y2014)

   Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  A     Alabama              1296530 1317711 1118631 1492583 1107408 1440134
2  A     Alaska               1170302 1960378 1818085 1447852 1861639 1465841
3  A     Arizona              1742027 1968140 1377583 1782199 1102568 1109382
4  A     Arkansas             1485531 1994927 1119299 1947979 1669191 1801213
5  C     California           1685349 1675807 1889570 1480280 1735069 1812546
6  C     Colorado             1343824 1878473 1886149 1236697 1871471 1814218
7  C     Connecticut          1610512 1232844 1181949 1518933 1841266 1976976
8  D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
9  D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
10 F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
11 G     Georgia              1929009 1541565 1810773 1779091 1326846 1223770
12 H     Hawaii               1461570 1200280 1213993 1245931 1459383 1430465
13 I     Idaho                1353210 1438538 1739154 1541015 1122387 1772050
14 I     Illinois             1508356 1527440 1493029 1261353 1540274 1747614
15 I     Indiana              1776918 1734104 1269927 1204117 1848073 1129546
16 I     Iowa                 1499269 1444576 1576367 1388924 1554813 1452911
17 K     Kansas               1509054 1290700 1522230 1532094 1104256 1863278
18 K     Kentucky             1813878 1448846 1800760 1250524 1137913 1911227
19 L     Louisiana            1584734 1110625 1868456 1751920 1233709 1920301
20 M     Maine                1582720 1678622 1208496 1912040 1438549 1330014
21 M     Maryland             1579713 1404700 1849798 1397738 1310270 1789128
22 M     Massachusetts        1647582 1686259 1620601 1777250 1531641 1380529
23 M     Michigan             1295635 1149931 1601027 1340716 1729449 1567494
24 M     Minnesota            1729921 1675204 1903907 1561839 1985692 1148621
25 M     Mississippi          1983285 1292558 1631325 1943311 1354579 1731643
26 M     Missouri             1221316 1858368 1773451 1573967 1374863 1486197
27 M     Montana              1877154 1540099 1332722 1273327 1625721 1983568
28 N     Nebraska             1885081 1309769 1425527 1240465 1500594 1278272
29 N     Nevada               1426117 1114500 1119707 1758830 1694526 1765826
30 N     New Hampshire        1419776 1854370 1195119 1990062 1645430 1286967
31 N     New Jersey           1605532 1141514 1613550 1181452 1541327 1156804
32 N     New Mexico           1819239 1226057 1935991 1124400 1723493 1475985
33 N     New York             1395149 1611371 1170675 1446810 1426941 1463171
34 N     North Carolina       1616742 1292223 1482792 1532347 1158716 1827420
35 N     North Dakota         1618807 1510193 1876940 1443172 1425030 1868788
36 O     Ohio                 1802132 1648498 1441386 1670280 1534888 1314824
37 O     Oklahoma             1173918 1334639 1663622 1798714 1312574 1708245
38 O     Oregon               1794912 1726665 1805445 1133510 1502242 1419251
39 P     Pennsylvania         1320191 1446723 1218591 1122030 1971479 1563062
40 R     Rhode Island         1501744 1942942 1266657 1961923 1835983 1234040
41 S     South Carolina       1631522 1803455 1425193 1458191 1538731 1825195
42 S     South Dakota         1159037 1150689 1660148 1417141 1418586 1279134
43 T     Tennessee            1811867 1485909 1974179 1157059 1786132 1399191
44 T     Texas                1520591 1310777 1957713 1907326 1873544 1655483
45 U     Utah                 1771096 1195861 1979395 1241662 1437456 1859416
46 V     Vermont              1146902 1832249 1492704 1579265 1332048 1563537
47 V     Virginia             1134317 1163996 1891068 1853855 1708715 1197698
48 W     Washington           1977749 1687136 1199490 1163092 1334864 1621989
49 W     West Virginia        1677347 1380662 1176100 1888948 1922085 1740826
50 W     Wisconsin            1788920 1518578 1289663 1436888 1251678 1721874
51 W     Wyoming              1775190 1498098 1198212 1881688 1750527 1523124
   Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015   new
1  1945229 1944173 1237582 1440756 1186741 1852841 1558906 1916661 1.2294911
2  1551826 1436541 1629616 1230866 1512804 1985302 1580394 1979143 1.2523099
3  1752886 1554330 1300521 1130709 1907284 1363279 1525866 1647724 1.0798615
4  1188104 1628980 1669295 1928238 1216675 1591896 1360959 1329341 0.9767679
5  1487315 1663809 1624509 1639670 1921845 1156536 1388461 1644607 1.1844820
6  1875146 1752387 1913275 1665877 1491604 1178355 1383978 1330736 0.9615297
7  1764457 1972730 1968730 1945524 1228529 1582249 1503156 1718072 1.1429765
8  1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508 0.9025821
9  1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183 0.7912734
10 1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389 0.8313697
11 1773090 1630325 1145473 1851245 1850111 1887157 1259353 1725470 1.3701242
12 1919423 1928416 1330509 1902816 1695126 1517184 1948108 1150882 0.5907691
13 1335481 1748608 1436809 1456340 1643855 1312561 1713718 1757171 1.0253560
14 1871645 1658551 1422021 1751422 1696729 1915435 1645465 1583516 0.9623517
15 1139551 1883976 1999102 1559924 1905760 1129794 1988394 1467614 0.7380901
16 1317983 1150783 1751389 1992996 1501879 1173694 1431705 1641866 1.1467907
17 1949478 1561528 1550433 1465812 1882929 1410249 1930090 1385528 0.7178567
18 1301848 1956681 1350895 1512894 1916616 1878271 1722762 1913350 1.1106293
19 1185085 1124853 1498662 1210385 1234234 1287663 1908602 1403857 0.7355420
20 1295877 1969163 1627262 1706080 1437088 1318546 1116792 1529233 1.3693087
21 1112765 1967225 1486246 1872327 1175819 1314343 1979529 1569566 0.7928987
22 1978904 1567651 1761048 1658538 1482203 1731917 1669749 1963337 1.1758276
23 1990431 1575185 1267626 1274673 1709853 1815596 1965196 1646634 0.8378981
24 1328133 1890633 1995304 1575533 1910216 1972021 1515366 1864553 1.2304308
25 1428291 1568049 1383227 1629132 1988270 1907777 1649668 1991232 1.2070501
26 1735099 1800620 1164202 1425363 1800052 1698105 1767835 1996005 1.1290675
27 1251742 1592690 1350619 1520064 1185225 1465705 1110394 1125903 1.0139671
28 1140598 1270585 1128711 1187207 1569665 1690920 1459243 1802211 1.2350315
29 1903270 1231480 1526066 1143343 1980195 1283813 1225348 1903804 1.5536843
30 1762936 1763211 1265642 1704297 1131298 1197576 1242623 1963313 1.5799748
31 1568034 1357418 1443718 1390010 1202326 1100990 1850165 1183568 0.6397094
32 1237704 1820856 1801430 1653384 1475715 1623388 1533494 1868612 1.2185323
33 1732098 1426216 1604531 1683687 1500089 1718837 1619033 1367705 0.8447666
34 1267737 1116168 1791535 1553750 1472258 1104893 1596452 1229085 0.7698853
35 1720352 1671468 1534571 1271132 1430978 1529024 1563898 1604118 1.0257178
36 1516621 1511460 1585465 1887714 1227303 1840898 1880804 1573117 0.8364067
37 1256746 1853142 1673831 1822933 1674707 1900523 1956742 1307678 0.6682935
38 1482786 1862351 1103794 1935687 1905378 1522129 1509171 1893515 1.2546723
39 1274168 1571032 1433835 1483292 1290329 1475344 1931500 1668232 0.8636976
40 1151409 1993136 1983569 1781016 1909119 1531212 1990412 1611730 0.8097469
41 1250499 1864685 1345102 1116203 1532332 1591735 1188417 1110655 0.9345667
42 1171870 1852424 1554782 1647245 1811156 1147488 1302834 1136443 0.8722853
43 1826406 1326460 1231739 1469785 1849041 1560887 1349173 1162164 0.8613899
44 1785986 1827503 1447457 1978374 1882532 1698698 1646508 1705322 1.0357204
45 1939284 1915865 1619186 1288285 1108281 1123353 1801019 1729273 0.9601637
46 1123567 1618583 1326369 1792600 1714960 1146278 1282790 1565924 1.2207173
47 1803330 1590043 1516758 1171686 1262342 1647032 1706707 1850394 1.0841896
48 1545621 1555554 1179331 1150089 1775787 1273834 1387428 1377341 0.9927297
49 1238174 1539322 1539603 1872519 1462137 1683127 1204344 1198791 0.9953892
50 1980167 1901394 1648755 1940943 1729177 1510119 1701650 1846238 1.0849693
51 1587602 1504455 1282142 1881814 1673668 1994022 1204029 1853858 1.5397121

In [43]:
mutate_all(dataset, funs("new" = .* 1000))

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

ERROR: Error in `mutate()`:
ℹ In argument: `Index_new = Index * 1000`.
Caused by error in `Index * 1000`:
! non-numeric argument to binary operator

In [44]:
mutate_if(dataset, is.numeric, funs("new" = .* 1000))

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

   Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  A     Alabama              1296530 1317711 1118631 1492583 1107408 1440134
2  A     Alaska               1170302 1960378 1818085 1447852 1861639 1465841
3  A     Arizona              1742027 1968140 1377583 1782199 1102568 1109382
4  A     Arkansas             1485531 1994927 1119299 1947979 1669191 1801213
5  C     California           1685349 1675807 1889570 1480280 1735069 1812546
6  C     Colorado             1343824 1878473 1886149 1236697 1871471 1814218
7  C     Connecticut          1610512 1232844 1181949 1518933 1841266 1976976
8  D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
9  D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
10 F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
11 G     Georgia              1929009 1541565 1810773 1779091 1326846 1223770
12 H     Hawaii               1461570 1200280 1213993 1245931 1459383 1430465
13 I     Idaho                1353210 1438538 1739154 1541015 1122387 1772050
14 I     Illinois             1508356 1527440 1493029 1261353 1540274 1747614
15 I     Indiana              1776918 1734104 1269927 1204117 1848073 1129546
16 I     Iowa                 1499269 1444576 1576367 1388924 1554813 1452911
17 K     Kansas               1509054 1290700 1522230 1532094 1104256 1863278
18 K     Kentucky             1813878 1448846 1800760 1250524 1137913 1911227
19 L     Louisiana            1584734 1110625 1868456 1751920 1233709 1920301
20 M     Maine                1582720 1678622 1208496 1912040 1438549 1330014
21 M     Maryland             1579713 1404700 1849798 1397738 1310270 1789128
22 M     Massachusetts        1647582 1686259 1620601 1777250 1531641 1380529
23 M     Michigan             1295635 1149931 1601027 1340716 1729449 1567494
24 M     Minnesota            1729921 1675204 1903907 1561839 1985692 1148621
25 M     Mississippi          1983285 1292558 1631325 1943311 1354579 1731643
26 M     Missouri             1221316 1858368 1773451 1573967 1374863 1486197
27 M     Montana              1877154 1540099 1332722 1273327 1625721 1983568
28 N     Nebraska             1885081 1309769 1425527 1240465 1500594 1278272
29 N     Nevada               1426117 1114500 1119707 1758830 1694526 1765826
30 N     New Hampshire        1419776 1854370 1195119 1990062 1645430 1286967
31 N     New Jersey           1605532 1141514 1613550 1181452 1541327 1156804
32 N     New Mexico           1819239 1226057 1935991 1124400 1723493 1475985
33 N     New York             1395149 1611371 1170675 1446810 1426941 1463171
34 N     North Carolina       1616742 1292223 1482792 1532347 1158716 1827420
35 N     North Dakota         1618807 1510193 1876940 1443172 1425030 1868788
36 O     Ohio                 1802132 1648498 1441386 1670280 1534888 1314824
37 O     Oklahoma             1173918 1334639 1663622 1798714 1312574 1708245
38 O     Oregon               1794912 1726665 1805445 1133510 1502242 1419251
39 P     Pennsylvania         1320191 1446723 1218591 1122030 1971479 1563062
40 R     Rhode Island         1501744 1942942 1266657 1961923 1835983 1234040
41 S     South Carolina       1631522 1803455 1425193 1458191 1538731 1825195
42 S     South Dakota         1159037 1150689 1660148 1417141 1418586 1279134
43 T     Tennessee            1811867 1485909 1974179 1157059 1786132 1399191
44 T     Texas                1520591 1310777 1957713 1907326 1873544 1655483
45 U     Utah                 1771096 1195861 1979395 1241662 1437456 1859416
46 V     Vermont              1146902 1832249 1492704 1579265 1332048 1563537
47 V     Virginia             1134317 1163996 1891068 1853855 1708715 1197698
48 W     Washington           1977749 1687136 1199490 1163092 1334864 1621989
49 W     West Virginia        1677347 1380662 1176100 1888948 1922085 1740826
50 W     Wisconsin            1788920 1518578 1289663 1436888 1251678 1721874
51 W     Wyoming              1775190 1498098 1198212 1881688 1750527 1523124
   Y2008   Y2009   ⋯ Y2006_new  Y2007_new  Y2008_new  Y2009_new  Y2010_new
1  1945229 1944173 ⋯ 1107408000 1440134000 1945229000 1944173000 1237582000
2  1551826 1436541 ⋯ 1861639000 1465841000 1551826000 1436541000 1629616000
3  1752886 1554330 ⋯ 1102568000 1109382000 1752886000 1554330000 1300521000
4  1188104 1628980 ⋯ 1669191000 1801213000 1188104000 1628980000 1669295000
5  1487315 1663809 ⋯ 1735069000 1812546000 1487315000 1663809000 1624509000
6  1875146 1752387 ⋯ 1871471000 1814218000 1875146000 1752387000 1913275000
7  1764457 1972730 ⋯ 1841266000 1976976000 1764457000 1972730000 1968730000
8  1762096 1553585 ⋯ 1441351000 1300836000 1762096000 1553585000 1370984000
9  1193245 1739748 ⋯ 1803852000 1595981000 1193245000 1739748000 1707823000
10 1756185 1818438 ⋯ 1339608000 1278550000 1756185000 1818438000 1198403000
11 1773090 1630325 ⋯ 1326846000 1223770000 1773090000 1630325000 1145473000
12 1919423 1928416 ⋯ 1459383000 1430465000 1919423000 1928416000 1330509000
13 1335481 1748608 ⋯ 1122387000 1772050000 1335481000 1748608000 1436809000
14 1871645 1658551 ⋯ 1540274000 1747614000 1871645000 1658551000 1422021000
15 1139551 1883976 ⋯ 1848073000 1129546000 1139551000 1883976000 1999102000
16 1317983 1150783 ⋯ 1554813000 1452911000 1317983000 1150783000 1751389000
17 1949478 1561528 ⋯ 1104256000 1863278000 1949478000 1561528000 1550433000
18 1301848 1956681 ⋯ 1137913000 1911227000 1301848000 1956681000 1350895000
19 1185085 1124853 ⋯ 1233709000 1920301000 1185085000 1124853000 1498662000
20 1295877 1969163 ⋯ 1438549000 1330014000 1295877000 1969163000 1627262000
21 1112765 1967225 ⋯ 1310270000 1789128000 1112765000 1967225000 1486246000
22 1978904 1567651 ⋯ 1531641000 1380529000 1978904000 1567651000 1761048000
23 1990431 1575185 ⋯ 1729449000 1567494000 1990431000 1575185000 1267626000
24 1328133 1890633 ⋯ 1985692000 1148621000 1328133000 1890633000 1995304000
25 1428291 1568049 ⋯ 1354579000 1731643000 1428291000 1568049000 1383227000
26 1735099 1800620 ⋯ 1374863000 1486197000 1735099000 1800620000 1164202000
27 1251742 1592690 ⋯ 1625721000 1983568000 1251742000 1592690000 1350619000
28 1140598 1270585 ⋯ 1500594000 1278272000 1140598000 1270585000 1128711000
29 1903270 1231480 ⋯ 1694526000 1765826000 1903270000 1231480000 1526066000
30 1762936 1763211 ⋯ 1645430000 1286967000 1762936000 1763211000 1265642000
31 1568034 1357418 ⋯ 1541327000 1156804000 1568034000 1357418000 1443718000
32 1237704 1820856 ⋯ 1723493000 1475985000 1237704000 1820856000 1801430000
33 1732098 1426216 ⋯ 1426941000 1463171000 1732098000 1426216000 1604531000
34 1267737 1116168 ⋯ 1158716000 1827420000 1267737000 1116168000 1791535000
35 1720352 1671468 ⋯ 1425030000 1868788000 1720352000 1671468000 1534571000
36 1516621 1511460 ⋯ 1534888000 1314824000 1516621000 1511460000 1585465000
37 1256746 1853142 ⋯ 1312574000 1708245000 1256746000 1853142000 1673831000
38 1482786 1862351 ⋯ 1502242000 1419251000 1482786000 1862351000 1103794000
39 1274168 1571032 ⋯ 1971479000 1563062000 1274168000 1571032000 1433835000
40 1151409 1993136 ⋯ 1835983000 1234040000 1151409000 1993136000 1983569000
41 1250499 1864685 ⋯ 1538731000 1825195000 1250499000 1864685000 1345102000
42 1171870 1852424 ⋯ 1418586000 1279134000 1171870000 1852424000 1554782000
43 1826406 1326460 ⋯ 1786132000 1399191000 1826406000 1326460000 1231739000
44 1785986 1827503 ⋯ 1873544000 1655483000 1785986000 1827503000 1447457000
45 1939284 1915865 ⋯ 1437456000 1859416000 1939284000 1915865000 1619186000
46 1123567 1618583 ⋯ 1332048000 1563537000 1123567000 1618583000 1326369000
47 1803330 1590043 ⋯ 1708715000 1197698000 1803330000 1590043000 1516758000
48 1545621 1555554 ⋯ 1334864000 1621989000 1545621000 1555554000 1179331000
49 1238174 1539322 ⋯ 1922085000 1740826000 1238174000 1539322000 1539603000
50 1980167 1901394 ⋯ 1251678000 1721874000 1980167000 1901394000 1648755000
51 1587602 1504455 ⋯ 1750527000 1523124000 1587602000 1504455000 1282142000
   Y2011_new  Y2012_new  Y2013_new  Y2014_new  Y2015_new
1  1440756000 1186741000 1852841000 1558906000 1916661000
2  1230866000 1512804000 1985302000 1580394000 1979143000
3  1130709000 1907284000 1363279000 1525866000 1647724000
4  1928238000 1216675000 1591896000 1360959000 1329341000
5  1639670000 1921845000 1156536000 1388461000 1644607000
6  1665877000 1491604000 1178355000 1383978000 1330736000
7  1945524000 1228529000 1582249000 1503156000 1718072000
8  1318669000 1984027000 1671279000 1803169000 1627508000
9  1353449000 1979708000 1912654000 1782169000 1410183000
10 1497051000 1131928000 1107448000 1407784000 1170389000
11 1851245000 1850111000 1887157000 1259353000 1725470000
12 1902816000 1695126000 1517184000 1948108000 1150882000
13 1456340000 1643855000 1312561000 1713718000 1757171000
14 1751422000 1696729000 1915435000 1645465000 1583516000
15 1559924000 1905760000 1129794000 1988394000 1467614000
16 1992996000 1501879000 1173694000 1431705000 1641866000
17 1465812000 1882929000 1410249000 1930090000 1385528000
18 1512894000 1916616000 1878271000 1722762000 1913350000
19 1210385000 1234234000 1287663000 1908602000 1403857000
20 1706080000 1437088000 1318546000 1116792000 1529233000
21 1872327000 1175819000 1314343000 1979529000 1569566000
22 1658538000 1482203000 1731917000 1669749000 1963337000
23 1274673000 1709853000 1815596000 1965196000 1646634000
24 1575533000 1910216000 1972021000 1515366000 1864553000
25 1629132000 1988270000 1907777000 1649668000 1991232000
26 1425363000 1800052000 1698105000 1767835000 1996005000
27 1520064000 1185225000 1465705000 1110394000 1125903000
28 1187207000 1569665000 1690920000 1459243000 1802211000
29 1143343000 1980195000 1283813000 1225348000 1903804000
30 1704297000 1131298000 1197576000 1242623000 1963313000
31 1390010000 1202326000 1100990000 1850165000 1183568000
32 1653384000 1475715000 1623388000 1533494000 1868612000
33 1683687000 1500089000 1718837000 1619033000 1367705000
34 1553750000 1472258000 1104893000 1596452000 1229085000
35 1271132000 1430978000 1529024000 1563898000 1604118000
36 1887714000 1227303000 1840898000 1880804000 1573117000
37 1822933000 1674707000 1900523000 1956742000 1307678000
38 1935687000 1905378000 1522129000 1509171000 1893515000
39 1483292000 1290329000 1475344000 1931500000 1668232000
40 1781016000 1909119000 1531212000 1990412000 1611730000
41 1116203000 1532332000 1591735000 1188417000 1110655000
42 1647245000 1811156000 1147488000 1302834000 1136443000
43 1469785000 1849041000 1560887000 1349173000 1162164000
44 1978374000 1882532000 1698698000 1646508000 1705322000
45 1288285000 1108281000 1123353000 1801019000 1729273000
46 1792600000 1714960000 1146278000 1282790000 1565924000
47 1171686000 1262342000 1647032000 1706707000 1850394000
48 1150089000 1775787000 1273834000 1387428000 1377341000
49 1872519000 1462137000 1683127000 1204344000 1198791000
50 1940943000 1729177000 1510119000 1701650000 1846238000
51 1881814000 1673668000 1994022000 1204029000 1853858000

In [45]:
mutate_at(dataset, vars(Y2008:Y2010), funs(Rank=min_rank(.)))

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

   Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  A     Alabama              1296530 1317711 1118631 1492583 1107408 1440134
2  A     Alaska               1170302 1960378 1818085 1447852 1861639 1465841
3  A     Arizona              1742027 1968140 1377583 1782199 1102568 1109382
4  A     Arkansas             1485531 1994927 1119299 1947979 1669191 1801213
5  C     California           1685349 1675807 1889570 1480280 1735069 1812546
6  C     Colorado             1343824 1878473 1886149 1236697 1871471 1814218
7  C     Connecticut          1610512 1232844 1181949 1518933 1841266 1976976
8  D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
9  D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
10 F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
11 G     Georgia              1929009 1541565 1810773 1779091 1326846 1223770
12 H     Hawaii               1461570 1200280 1213993 1245931 1459383 1430465
13 I     Idaho                1353210 1438538 1739154 1541015 1122387 1772050
14 I     Illinois             1508356 1527440 1493029 1261353 1540274 1747614
15 I     Indiana              1776918 1734104 1269927 1204117 1848073 1129546
16 I     Iowa                 1499269 1444576 1576367 1388924 1554813 1452911
17 K     Kansas               1509054 1290700 1522230 1532094 1104256 1863278
18 K     Kentucky             1813878 1448846 1800760 1250524 1137913 1911227
19 L     Louisiana            1584734 1110625 1868456 1751920 1233709 1920301
20 M     Maine                1582720 1678622 1208496 1912040 1438549 1330014
21 M     Maryland             1579713 1404700 1849798 1397738 1310270 1789128
22 M     Massachusetts        1647582 1686259 1620601 1777250 1531641 1380529
23 M     Michigan             1295635 1149931 1601027 1340716 1729449 1567494
24 M     Minnesota            1729921 1675204 1903907 1561839 1985692 1148621
25 M     Mississippi          1983285 1292558 1631325 1943311 1354579 1731643
26 M     Missouri             1221316 1858368 1773451 1573967 1374863 1486197
27 M     Montana              1877154 1540099 1332722 1273327 1625721 1983568
28 N     Nebraska             1885081 1309769 1425527 1240465 1500594 1278272
29 N     Nevada               1426117 1114500 1119707 1758830 1694526 1765826
30 N     New Hampshire        1419776 1854370 1195119 1990062 1645430 1286967
31 N     New Jersey           1605532 1141514 1613550 1181452 1541327 1156804
32 N     New Mexico           1819239 1226057 1935991 1124400 1723493 1475985
33 N     New York             1395149 1611371 1170675 1446810 1426941 1463171
34 N     North Carolina       1616742 1292223 1482792 1532347 1158716 1827420
35 N     North Dakota         1618807 1510193 1876940 1443172 1425030 1868788
36 O     Ohio                 1802132 1648498 1441386 1670280 1534888 1314824
37 O     Oklahoma             1173918 1334639 1663622 1798714 1312574 1708245
38 O     Oregon               1794912 1726665 1805445 1133510 1502242 1419251
39 P     Pennsylvania         1320191 1446723 1218591 1122030 1971479 1563062
40 R     Rhode Island         1501744 1942942 1266657 1961923 1835983 1234040
41 S     South Carolina       1631522 1803455 1425193 1458191 1538731 1825195
42 S     South Dakota         1159037 1150689 1660148 1417141 1418586 1279134
43 T     Tennessee            1811867 1485909 1974179 1157059 1786132 1399191
44 T     Texas                1520591 1310777 1957713 1907326 1873544 1655483
45 U     Utah                 1771096 1195861 1979395 1241662 1437456 1859416
46 V     Vermont              1146902 1832249 1492704 1579265 1332048 1563537
47 V     Virginia             1134317 1163996 1891068 1853855 1708715 1197698
48 W     Washington           1977749 1687136 1199490 1163092 1334864 1621989
49 W     West Virginia        1677347 1380662 1176100 1888948 1922085 1740826
50 W     Wisconsin            1788920 1518578 1289663 1436888 1251678 1721874
51 W     Wyoming              1775190 1498098 1198212 1881688 1750527 1523124
   Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015   Y2008_Rank
1  1945229 1944173 1237582 1440756 1186741 1852841 1558906 1916661 47
2  1551826 1436541 1629616 1230866 1512804 1985302 1580394 1979143 27
3  1752886 1554330 1300521 1130709 1907284 1363279 1525866 1647724 33
4  1188104 1628980 1669295 1928238 1216675 1591896 1360959 1329341  8
5  1487315 1663809 1624509 1639670 1921845 1156536 1388461 1644607 24
6  1875146 1752387 1913275 1665877 1491604 1178355 1383978 1330736 43
7  1764457 1972730 1968730 1945524 1228529 1582249 1503156 1718072 37
8  1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508 35
9  1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183  9
10 1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389 34
11 1773090 1630325 1145473 1851245 1850111 1887157 1259353 1725470 38
12 1919423 1928416 1330509 1902816 1695126 1517184 1948108 1150882 45
13 1335481 1748608 1436809 1456340 1643855 1312561 1713718 1757171 21
14 1871645 1658551 1422021 1751422 1696729 1915435 1645465 1583516 42
15 1139551 1883976 1999102 1559924 1905760 1129794 1988394 1467614  3
16 1317983 1150783 1751389 1992996 1501879 1173694 1431705 1641866 19
17 1949478 1561528 1550433 1465812 1882929 1410249 1930090 1385528 48
18 1301848 1956681 1350895 1512894 1916616 1878271 1722762 1913350 18
19 1185085 1124853 1498662 1210385 1234234 1287663 1908602 1403857  7
20 1295877 1969163 1627262 1706080 1437088 1318546 1116792 1529233 17
21 1112765 1967225 1486246 1872327 1175819 1314343 1979529 1569566  1
22 1978904 1567651 1761048 1658538 1482203 1731917 1669749 1963337 49
23 1990431 1575185 1267626 1274673 1709853 1815596 1965196 1646634 51
24 1328133 1890633 1995304 1575533 1910216 1972021 1515366 1864553 20
25 1428291 1568049 1383227 1629132 1988270 1907777 1649668 1991232 22
26 1735099 1800620 1164202 1425363 1800052 1698105 1767835 1996005 32
27 1251742 1592690 1350619 1520064 1185225 1465705 1110394 1125903 13
28 1140598 1270585 1128711 1187207 1569665 1690920 1459243 1802211  4
29 1903270 1231480 1526066 1143343 1980195 1283813 1225348 1903804 44
30 1762936 1763211 1265642 1704297 1131298 1197576 1242623 1963313 36
31 1568034 1357418 1443718 1390010 1202326 1100990 1850165 1183568 28
32 1237704 1820856 1801430 1653384 1475715 1623388 1533494 1868612 10
33 1732098 1426216 1604531 1683687 1500089 1718837 1619033 1367705 31
34 1267737 1116168 1791535 1553750 1472258 1104893 1596452 1229085 15
35 1720352 1671468 1534571 1271132 1430978 1529024 1563898 1604118 30
36 1516621 1511460 1585465 1887714 1227303 1840898 1880804 1573117 25
37 1256746 1853142 1673831 1822933 1674707 1900523 1956742 1307678 14
38 1482786 1862351 1103794 1935687 1905378 1522129 1509171 1893515 23
39 1274168 1571032 1433835 1483292 1290329 1475344 1931500 1668232 16
40 1151409 1993136 1983569 1781016 1909119 1531212 1990412 1611730  5
41 1250499 1864685 1345102 1116203 1532332 1591735 1188417 1110655 12
42 1171870 1852424 1554782 1647245 1811156 1147488 1302834 1136443  6
43 1826406 1326460 1231739 1469785 1849041 1560887 1349173 1162164 41
44 1785986 1827503 1447457 1978374 1882532 1698698 1646508 1705322 39
45 1939284 1915865 1619186 1288285 1108281 1123353 1801019 1729273 46
46 1123567 1618583 1326369 1792600 1714960 1146278 1282790 1565924  2
47 1803330 1590043 1516758 1171686 1262342 1647032 1706707 1850394 40
48 1545621 1555554 1179331 1150089 1775787 1273834 1387428 1377341 26
49 1238174 1539322 1539603 1872519 1462137 1683127 1204344 1198791 11
50 1980167 1901394 1648755 1940943 1729177 1510119 1701650 1846238 50
51 1587602 1504455 1282142 1881814 1673668 1994022 1204029 1853858 29
   Y2009_Rank Y2010_Rank
1  46          8
2   9         38
3  14         12
4  24         40
5  27         36
6  31         47
7  50         48
8  13         18
9  29         42
10 34          6
11 25          3
12 45         14
13 30         22
14 26         20
15 41         51
16  3         43
17 16         31
18 47         17
19  2         26
20 49         37
21 48         25
22 17         44
23 20         10
24 42         50
25 18         19
26 33          4
27 22         16
28  5          2
29  4         28
30 32          9
31  7         23
32 35         46
33  8         34
34  1         45
35 28         29
36 11         33
37 38         41
38 39          1
39 19         21
40 51         49
41 40         15
42 37         32
43  6          7
44 36         24
45 44         35
46 23         13
47 21         27
48 15          5
49 12         30
50 43         39
51 10         11

In [46]:
mutate_at(dataset, vars(Y2008:Y2010), funs(Rank=min_rank(desc(.))))

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

   Index State                Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1  A     Alabama              1296530 1317711 1118631 1492583 1107408 1440134
2  A     Alaska               1170302 1960378 1818085 1447852 1861639 1465841
3  A     Arizona              1742027 1968140 1377583 1782199 1102568 1109382
4  A     Arkansas             1485531 1994927 1119299 1947979 1669191 1801213
5  C     California           1685349 1675807 1889570 1480280 1735069 1812546
6  C     Colorado             1343824 1878473 1886149 1236697 1871471 1814218
7  C     Connecticut          1610512 1232844 1181949 1518933 1841266 1976976
8  D     Delaware             1330403 1268673 1706751 1403759 1441351 1300836
9  D     District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
10 F     Florida              1964626 1468852 1419738 1362787 1339608 1278550
11 G     Georgia              1929009 1541565 1810773 1779091 1326846 1223770
12 H     Hawaii               1461570 1200280 1213993 1245931 1459383 1430465
13 I     Idaho                1353210 1438538 1739154 1541015 1122387 1772050
14 I     Illinois             1508356 1527440 1493029 1261353 1540274 1747614
15 I     Indiana              1776918 1734104 1269927 1204117 1848073 1129546
16 I     Iowa                 1499269 1444576 1576367 1388924 1554813 1452911
17 K     Kansas               1509054 1290700 1522230 1532094 1104256 1863278
18 K     Kentucky             1813878 1448846 1800760 1250524 1137913 1911227
19 L     Louisiana            1584734 1110625 1868456 1751920 1233709 1920301
20 M     Maine                1582720 1678622 1208496 1912040 1438549 1330014
21 M     Maryland             1579713 1404700 1849798 1397738 1310270 1789128
22 M     Massachusetts        1647582 1686259 1620601 1777250 1531641 1380529
23 M     Michigan             1295635 1149931 1601027 1340716 1729449 1567494
24 M     Minnesota            1729921 1675204 1903907 1561839 1985692 1148621
25 M     Mississippi          1983285 1292558 1631325 1943311 1354579 1731643
26 M     Missouri             1221316 1858368 1773451 1573967 1374863 1486197
27 M     Montana              1877154 1540099 1332722 1273327 1625721 1983568
28 N     Nebraska             1885081 1309769 1425527 1240465 1500594 1278272
29 N     Nevada               1426117 1114500 1119707 1758830 1694526 1765826
30 N     New Hampshire        1419776 1854370 1195119 1990062 1645430 1286967
31 N     New Jersey           1605532 1141514 1613550 1181452 1541327 1156804
32 N     New Mexico           1819239 1226057 1935991 1124400 1723493 1475985
33 N     New York             1395149 1611371 1170675 1446810 1426941 1463171
34 N     North Carolina       1616742 1292223 1482792 1532347 1158716 1827420
35 N     North Dakota         1618807 1510193 1876940 1443172 1425030 1868788
36 O     Ohio                 1802132 1648498 1441386 1670280 1534888 1314824
37 O     Oklahoma             1173918 1334639 1663622 1798714 1312574 1708245
38 O     Oregon               1794912 1726665 1805445 1133510 1502242 1419251
39 P     Pennsylvania         1320191 1446723 1218591 1122030 1971479 1563062
40 R     Rhode Island         1501744 1942942 1266657 1961923 1835983 1234040
41 S     South Carolina       1631522 1803455 1425193 1458191 1538731 1825195
42 S     South Dakota         1159037 1150689 1660148 1417141 1418586 1279134
43 T     Tennessee            1811867 1485909 1974179 1157059 1786132 1399191
44 T     Texas                1520591 1310777 1957713 1907326 1873544 1655483
45 U     Utah                 1771096 1195861 1979395 1241662 1437456 1859416
46 V     Vermont              1146902 1832249 1492704 1579265 1332048 1563537
47 V     Virginia             1134317 1163996 1891068 1853855 1708715 1197698
48 W     Washington           1977749 1687136 1199490 1163092 1334864 1621989
49 W     West Virginia        1677347 1380662 1176100 1888948 1922085 1740826
50 W     Wisconsin            1788920 1518578 1289663 1436888 1251678 1721874
51 W     Wyoming              1775190 1498098 1198212 1881688 1750527 1523124
   Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015   Y2008_Rank
1  1945229 1944173 1237582 1440756 1186741 1852841 1558906 1916661  5
2  1551826 1436541 1629616 1230866 1512804 1985302 1580394 1979143 25
3  1752886 1554330 1300521 1130709 1907284 1363279 1525866 1647724 19
4  1188104 1628980 1669295 1928238 1216675 1591896 1360959 1329341 44
5  1487315 1663809 1624509 1639670 1921845 1156536 1388461 1644607 28
6  1875146 1752387 1913275 1665877 1491604 1178355 1383978 1330736  9
7  1764457 1972730 1968730 1945524 1228529 1582249 1503156 1718072 15
8  1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508 17
9  1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183 43
10 1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389 18
11 1773090 1630325 1145473 1851245 1850111 1887157 1259353 1725470 14
12 1919423 1928416 1330509 1902816 1695126 1517184 1948108 1150882  7
13 1335481 1748608 1436809 1456340 1643855 1312561 1713718 1757171 31
14 1871645 1658551 1422021 1751422 1696729 1915435 1645465 1583516 10
15 1139551 1883976 1999102 1559924 1905760 1129794 1988394 1467614 49
16 1317983 1150783 1751389 1992996 1501879 1173694 1431705 1641866 33
17 1949478 1561528 1550433 1465812 1882929 1410249 1930090 1385528  4
18 1301848 1956681 1350895 1512894 1916616 1878271 1722762 1913350 34
19 1185085 1124853 1498662 1210385 1234234 1287663 1908602 1403857 45
20 1295877 1969163 1627262 1706080 1437088 1318546 1116792 1529233 35
21 1112765 1967225 1486246 1872327 1175819 1314343 1979529 1569566 51
22 1978904 1567651 1761048 1658538 1482203 1731917 1669749 1963337  3
23 1990431 1575185 1267626 1274673 1709853 1815596 1965196 1646634  1
24 1328133 1890633 1995304 1575533 1910216 1972021 1515366 1864553 32
25 1428291 1568049 1383227 1629132 1988270 1907777 1649668 1991232 30
26 1735099 1800620 1164202 1425363 1800052 1698105 1767835 1996005 20
27 1251742 1592690 1350619 1520064 1185225 1465705 1110394 1125903 39
28 1140598 1270585 1128711 1187207 1569665 1690920 1459243 1802211 48
29 1903270 1231480 1526066 1143343 1980195 1283813 1225348 1903804  8
30 1762936 1763211 1265642 1704297 1131298 1197576 1242623 1963313 16
31 1568034 1357418 1443718 1390010 1202326 1100990 1850165 1183568 24
32 1237704 1820856 1801430 1653384 1475715 1623388 1533494 1868612 42
33 1732098 1426216 1604531 1683687 1500089 1718837 1619033 1367705 21
34 1267737 1116168 1791535 1553750 1472258 1104893 1596452 1229085 37
35 1720352 1671468 1534571 1271132 1430978 1529024 1563898 1604118 22
36 1516621 1511460 1585465 1887714 1227303 1840898 1880804 1573117 27
37 1256746 1853142 1673831 1822933 1674707 1900523 1956742 1307678 38
38 1482786 1862351 1103794 1935687 1905378 1522129 1509171 1893515 29
39 1274168 1571032 1433835 1483292 1290329 1475344 1931500 1668232 36
40 1151409 1993136 1983569 1781016 1909119 1531212 1990412 1611730 47
41 1250499 1864685 1345102 1116203 1532332 1591735 1188417 1110655 40
42 1171870 1852424 1554782 1647245 1811156 1147488 1302834 1136443 46
43 1826406 1326460 1231739 1469785 1849041 1560887 1349173 1162164 11
44 1785986 1827503 1447457 1978374 1882532 1698698 1646508 1705322 13
45 1939284 1915865 1619186 1288285 1108281 1123353 1801019 1729273  6
46 1123567 1618583 1326369 1792600 1714960 1146278 1282790 1565924 50
47 1803330 1590043 1516758 1171686 1262342 1647032 1706707 1850394 12
48 1545621 1555554 1179331 1150089 1775787 1273834 1387428 1377341 26
49 1238174 1539322 1539603 1872519 1462137 1683127 1204344 1198791 41
50 1980167 1901394 1648755 1940943 1729177 1510119 1701650 1846238  2
51 1587602 1504455 1282142 1881814 1673668 1994022 1204029 1853858 23
   Y2009_Rank Y2010_Rank
1   6         44
2  43         14
3  38         40
4  28         12
5  25         16
6  21          5
7   2          4
8  39         34
9  23         10
10 18         46
11 27         49
12  7         38
13 22         30
14 26         32
15 11          1
16 49          9
17 36         21
18  5         35
19 50         26
20  3         15
21  4         27
22 35          8
23 32         42
24 10          2
25 34         33
26 19         48
27 30         36
28 47         50
29 48         24
30 20         43
31 45         29
32 17          6
33 44         18
34 51          7
35 24         23
36 41         19
37 14         11
38 13         51
39 33         31
40  1          3
41 12         37
42 15         20
43 46         45
44 16         28
45  8         17
46 29         39
47 31         25
48 37         47
49 40         22
50  9         13
51 42         41

<b> <li> rename variables / premenovanie atributov/ stlpcov </li></b>

In [47]:
rename(dataset, Zac.pismeno=Index)

   Zac.pismeno State                Y2002   Y2003   Y2004   Y2005   Y2006
1  A           Alabama              1296530 1317711 1118631 1492583 1107408
2  A           Alaska               1170302 1960378 1818085 1447852 1861639
3  A           Arizona              1742027 1968140 1377583 1782199 1102568
4  A           Arkansas             1485531 1994927 1119299 1947979 1669191
5  C           California           1685349 1675807 1889570 1480280 1735069
6  C           Colorado             1343824 1878473 1886149 1236697 1871471
7  C           Connecticut          1610512 1232844 1181949 1518933 1841266
8  D           Delaware             1330403 1268673 1706751 1403759 1441351
9  D           District of Columbia 1111437 1993741 1374643 1827949 1803852
10 F           Florida              1964626 1468852 1419738 1362787 1339608
11 G           Georgia              1929009 1541565 1810773 1779091 1326846
12 H           Hawaii               1461570 1200280 1213993 1245931 1459383
13 I           Idaho                1353210 1438538 1739154 1541015 1122387
14 I           Illinois             1508356 1527440 1493029 1261353 1540274
15 I           Indiana              1776918 1734104 1269927 1204117 1848073
16 I           Iowa                 1499269 1444576 1576367 1388924 1554813
17 K           Kansas               1509054 1290700 1522230 1532094 1104256
18 K           Kentucky             1813878 1448846 1800760 1250524 1137913
19 L           Louisiana            1584734 1110625 1868456 1751920 1233709
20 M           Maine                1582720 1678622 1208496 1912040 1438549
21 M           Maryland             1579713 1404700 1849798 1397738 1310270
22 M           Massachusetts        1647582 1686259 1620601 1777250 1531641
23 M           Michigan             1295635 1149931 1601027 1340716 1729449
24 M           Minnesota            1729921 1675204 1903907 1561839 1985692
25 M           Mississippi          1983285 1292558 1631325 1943311 1354579
26 M           Missouri             1221316 1858368 1773451 1573967 1374863
27 M           Montana              1877154 1540099 1332722 1273327 1625721
28 N           Nebraska             1885081 1309769 1425527 1240465 1500594
29 N           Nevada               1426117 1114500 1119707 1758830 1694526
30 N           New Hampshire        1419776 1854370 1195119 1990062 1645430
31 N           New Jersey           1605532 1141514 1613550 1181452 1541327
32 N           New Mexico           1819239 1226057 1935991 1124400 1723493
33 N           New York             1395149 1611371 1170675 1446810 1426941
34 N           North Carolina       1616742 1292223 1482792 1532347 1158716
35 N           North Dakota         1618807 1510193 1876940 1443172 1425030
36 O           Ohio                 1802132 1648498 1441386 1670280 1534888
37 O           Oklahoma             1173918 1334639 1663622 1798714 1312574
38 O           Oregon               1794912 1726665 1805445 1133510 1502242
39 P           Pennsylvania         1320191 1446723 1218591 1122030 1971479
40 R           Rhode Island         1501744 1942942 1266657 1961923 1835983
41 S           South Carolina       1631522 1803455 1425193 1458191 1538731
42 S           South Dakota         1159037 1150689 1660148 1417141 1418586
43 T           Tennessee            1811867 1485909 1974179 1157059 1786132
44 T           Texas                1520591 1310777 1957713 1907326 1873544
45 U           Utah                 1771096 1195861 1979395 1241662 1437456
46 V           Vermont              1146902 1832249 1492704 1579265 1332048
47 V           Virginia             1134317 1163996 1891068 1853855 1708715
48 W           Washington           1977749 1687136 1199490 1163092 1334864
49 W           West Virginia        1677347 1380662 1176100 1888948 1922085
50 W           Wisconsin            1788920 1518578 1289663 1436888 1251678
51 W           Wyoming              1775190 1498098 1198212 1881688 1750527
   Y2007   Y2008   Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1  1440134 1945229 1944173 1237582 1440756 1186741 1852841 1558906 1916661
2  1465841 1551826 1436541 1629616 1230866 1512804 1985302 1580394 1979143
3  1109382 1752886 1554330 1300521 1130709 1907284 1363279 1525866 1647724
4  1801213 1188104 1628980 1669295 1928238 1216675 1591896 1360959 1329341
5  1812546 1487315 1663809 1624509 1639670 1921845 1156536 1388461 1644607
6  1814218 1875146 1752387 1913275 1665877 1491604 1178355 1383978 1330736
7  1976976 1764457 1972730 1968730 1945524 1228529 1582249 1503156 1718072
8  1300836 1762096 1553585 1370984 1318669 1984027 1671279 1803169 1627508
9  1595981 1193245 1739748 1707823 1353449 1979708 1912654 1782169 1410183
10 1278550 1756185 1818438 1198403 1497051 1131928 1107448 1407784 1170389
11 1223770 1773090 1630325 1145473 1851245 1850111 1887157 1259353 1725470
12 1430465 1919423 1928416 1330509 1902816 1695126 1517184 1948108 1150882
13 1772050 1335481 1748608 1436809 1456340 1643855 1312561 1713718 1757171
14 1747614 1871645 1658551 1422021 1751422 1696729 1915435 1645465 1583516
15 1129546 1139551 1883976 1999102 1559924 1905760 1129794 1988394 1467614
16 1452911 1317983 1150783 1751389 1992996 1501879 1173694 1431705 1641866
17 1863278 1949478 1561528 1550433 1465812 1882929 1410249 1930090 1385528
18 1911227 1301848 1956681 1350895 1512894 1916616 1878271 1722762 1913350
19 1920301 1185085 1124853 1498662 1210385 1234234 1287663 1908602 1403857
20 1330014 1295877 1969163 1627262 1706080 1437088 1318546 1116792 1529233
21 1789128 1112765 1967225 1486246 1872327 1175819 1314343 1979529 1569566
22 1380529 1978904 1567651 1761048 1658538 1482203 1731917 1669749 1963337
23 1567494 1990431 1575185 1267626 1274673 1709853 1815596 1965196 1646634
24 1148621 1328133 1890633 1995304 1575533 1910216 1972021 1515366 1864553
25 1731643 1428291 1568049 1383227 1629132 1988270 1907777 1649668 1991232
26 1486197 1735099 1800620 1164202 1425363 1800052 1698105 1767835 1996005
27 1983568 1251742 1592690 1350619 1520064 1185225 1465705 1110394 1125903
28 1278272 1140598 1270585 1128711 1187207 1569665 1690920 1459243 1802211
29 1765826 1903270 1231480 1526066 1143343 1980195 1283813 1225348 1903804
30 1286967 1762936 1763211 1265642 1704297 1131298 1197576 1242623 1963313
31 1156804 1568034 1357418 1443718 1390010 1202326 1100990 1850165 1183568
32 1475985 1237704 1820856 1801430 1653384 1475715 1623388 1533494 1868612
33 1463171 1732098 1426216 1604531 1683687 1500089 1718837 1619033 1367705
34 1827420 1267737 1116168 1791535 1553750 1472258 1104893 1596452 1229085
35 1868788 1720352 1671468 1534571 1271132 1430978 1529024 1563898 1604118
36 1314824 1516621 1511460 1585465 1887714 1227303 1840898 1880804 1573117
37 1708245 1256746 1853142 1673831 1822933 1674707 1900523 1956742 1307678
38 1419251 1482786 1862351 1103794 1935687 1905378 1522129 1509171 1893515
39 1563062 1274168 1571032 1433835 1483292 1290329 1475344 1931500 1668232
40 1234040 1151409 1993136 1983569 1781016 1909119 1531212 1990412 1611730
41 1825195 1250499 1864685 1345102 1116203 1532332 1591735 1188417 1110655
42 1279134 1171870 1852424 1554782 1647245 1811156 1147488 1302834 1136443
43 1399191 1826406 1326460 1231739 1469785 1849041 1560887 1349173 1162164
44 1655483 1785986 1827503 1447457 1978374 1882532 1698698 1646508 1705322
45 1859416 1939284 1915865 1619186 1288285 1108281 1123353 1801019 1729273
46 1563537 1123567 1618583 1326369 1792600 1714960 1146278 1282790 1565924
47 1197698 1803330 1590043 1516758 1171686 1262342 1647032 1706707 1850394
48 1621989 1545621 1555554 1179331 1150089 1775787 1273834 1387428 1377341
49 1740826 1238174 1539322 1539603 1872519 1462137 1683127 1204344 1198791
50 1721874 1980167 1901394 1648755 1940943 1729177 1510119 1701650 1846238
51 1523124 1587602 1504455 1282142 1881814 1673668 1994022 1204029 1853858

## 3. Summarise Cases 

Mnoho úloh v oblasti analýzy dát sa dá vyjadriť pomocou paradigmy <samp> **split-apply-combine**</samp> = <samp>**rozdeliť-použiť-skombinovať**</samp>:
rozdeliť údaje do skupín, použiť určitú analýzu pre každú skupinu a potom skombinovať výsledky. 
  
 
<code>dplyr</code> ponúka <code>group_by()</code> funkciu, ktorá rozdeľuje dáta do skupín. 
Ak sú dáta zoskupené týmto spôsobom, je možné použiť <code>summarize()</code> na vyvorenie jednoriadkového súhrnu z každej skupiny. 
Funkcia <code>summarize()</code>  použije pre každú skupinu agregačnú alebo súhrnnú funkciu. 

  <table class="table table-bordered table-striped">
    <thead>
      <tr><th>Funkcia </th><th> Popis</th></tr>
    </thead>
        <tr>
            <td class="text-nowrap"><code>group_by(dataframe, variables</code></td>
            <td> Zoskupi dáta avšak nezmení spôsob zobrazenia údajov </td>
          </tr>
      <tr>
        <td class="text-nowrap"><code>summarize(dataframe, summary function)</code></td>
        <td> Sumarizácia, agregácia údajov </td>
      </tr>
      <tr>
        <td class="text-nowrap"><code>summarize_at(dataframe, variables, summary function)</code></td>
        <td> Sumarizácia viacrých premenných, výber podľa ich názvu </td>
      </tr>
      <tr>
        <td class="text-nowrap"><code>summarize_if(dataframe, condition, summary function)</code></td>
        <td> Podmienená sumarizácia, summarizuje premenné vybrané pomocou zadanej podmienky</td>
        </tr>
        <tr>
          <td class="text-nowrap"><code>summarize_all(dataframe, summary function)</code></td>
          <td> Sumarizuje všetky atribúty </td>
        </tr>
  </table>

In [48]:
summarise(dataset, mean(Y2015), median(Y2015))

  mean(Y2015) median(Y2015)
1 1588297     1627508

In [49]:
summarise_at(dataset, vars(Y2005, Y2006), funs(n(), mean, median))

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

  Y2005_n Y2006_n Y2005_mean Y2006_mean Y2005_median Y2006_median
1 51      51      1522064    1530969    1480280      1531641

In [50]:
summarise_at(dataset, vars(Y2005, Y2006), list(~n(), ~mean(.), ~median(.)))

  Y2005_n Y2006_n Y2005_mean Y2006_mean Y2005_median Y2006_median
1 51      51      1522064    1530969    1480280      1531641

In [51]:
summarise_if(dataset, is.numeric, funs(n(),mean,median))

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

  Y2002_n Y2003_n Y2004_n Y2005_n Y2006_n Y2007_n Y2008_n Y2009_n Y2010_n
1 51      51      51      51      51      51      51      51      51
  Y2011_n ⋯ Y2006_median Y2007_median Y2008_median Y2009_median Y2010_median
1 51      ⋯ 1531641      1563062      1545621      1658551      1498662
  Y2011_median Y2012_median Y2013_median Y2014_median Y2015_median
1 1575533      1643855      1531212      1580394      1627508

In [52]:
summarise_all(dataset["Index"], funs(nlevels(.), nmiss=sum(is.na(.))))

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

  nlevels nmiss
1 0       0

## 4. Pipe Operator <code>%>%</code> syntax 

Pipe operátor je nástrojom pre ľahko čitateľné vyjadrenie postupnosti viacerých operácií. Vďaka pipe operátoru voláme jednotlivé operácie reťazovo. Jednoducho povedané, pipe operátor nám umožňuje preniesť priebežný výsledok na ďalšiu funkciu.

Kód v jazyku R často obsahuje mnoho zátvoriek, čím sa stáva neprehľadným. Pipe operátor vytvorí zo zložitých operácií čitateľný a zrozumiteľný kód. Ďalšou výhodou je, že sa môžete vyhnúť vnoreným volaniam, minimalizujete potrebu vnorených premenných a definicií funkcií a zároveň vám uľahčí pridávanie krokov kdekoľvek do postupnosti operácií.

Aj jednoduchú funckiu ako <code>log(x)</code> vieme prepísať ako <code>x %>% log()</code>. Princíp si ukážeme na nasledujúcich príkladoch:

In [53]:
sample_n(select(dataset, Index, State),10)

# or 

dataset %>% 
    select(Index, State) %>% 
    sample_n(10)

   Index State
1  L     Louisiana
2  O     Oklahoma
3  K     Kentucky
4  S     South Carolina
5  M     Michigan
6  W     Washington
7  O     Oregon
8  C     Colorado
9  I     Indiana
10 H     Hawaii

   Index State
1  D     Delaware
2  M     Maryland
3  N     Nevada
4  M     Michigan
5  W     Wyoming
6  W     Washington
7  N     New Mexico
8  D     District of Columbia
9  G     Georgia
10 T     Texas

In [54]:
summarise_at(group_by(dataset, Index), vars(Y2011, Y2012), funs(n()))

# or

dataset %>%
    group_by(Index) %>% 
    summarise_at(vars(Y2011:Y2012), funs(n()))

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

   Index Y2011 Y2012
1  A     4     4
2  C     3     3
3  D     2     2
4  F     1     1
5  G     1     1
6  H     1     1
7  I     4     4
8  K     2     2
9  L     1     1
10 M     8     8
11 N     8     8
12 O     3     3
13 P     1     1
14 R     1     1
15 S     2     2
16 T     2     2
17 U     1     1
18 V     2     2
19 W     4     4

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

   Index Y2011 Y2012
1  A     4     4
2  C     3     3
3  D     2     2
4  F     1     1
5  G     1     1
6  H     1     1
7  I     4     4
8  K     2     2
9  L     1     1
10 M     8     8
11 N     8     8
12 O     3     3
13 P     1     1
14 R     1     1
15 S     2     2
16 T     2     2
17 U     1     1
18 V     2     2
19 W     4     4

In [55]:
# function do()
dataset %>% 
    filter(Index %in% c("A", "C","I"))%>% 
    group_by(Index) %>% 
    do(head( . , 2))

  Index State      Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008
1 A     Alabama    1296530 1317711 1118631 1492583 1107408 1440134 1945229
2 A     Alaska     1170302 1960378 1818085 1447852 1861639 1465841 1551826
3 C     California 1685349 1675807 1889570 1480280 1735069 1812546 1487315
4 C     Colorado   1343824 1878473 1886149 1236697 1871471 1814218 1875146
5 I     Idaho      1353210 1438538 1739154 1541015 1122387 1772050 1335481
6 I     Illinois   1508356 1527440 1493029 1261353 1540274 1747614 1871645
  Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1 1944173 1237582 1440756 1186741 1852841 1558906 1916661
2 1436541 1629616 1230866 1512804 1985302 1580394 1979143
3 1663809 1624509 1639670 1921845 1156536 1388461 1644607
4 1752387 1913275 1665877 1491604 1178355 1383978 1330736
5 1748608 1436809 1456340 1643855 1312561 1713718 1757171
6 1658551 1422021 1751422 1696729 1915435 1645465 1583516

In [56]:
dataset %>%
    select(Index, Y2015) %>%  
    filter(Index %in% c("A", "C","I")) %>%  
    group_by(Index) %>% 
    do(arrange(.,desc(Y2015)))

   Index Y2015
1  A     1979143
2  A     1916661
3  A     1647724
4  A     1329341
5  C     1718072
6  C     1644607
7  C     1330736
8  I     1757171
9  I     1641866
10 I     1583516
11 I     1467614

In [57]:
dataset %>% 
    select(Index, Y2015) %>%  
    filter(Index %in% c("A", "C","I")) %>%  
    group_by(Index) %>% 
    do(arrange(.,desc(Y2015))) %>%  
    slice(3)

  Index Y2015
1 A     1647724
2 C     1330736
3 I     1583516

In [58]:
dataset %>% 
    group_by(Index) %>% 
    filter(min_rank(desc(Y2015)) == 1) %>% 
    select(Index, State, Y2015)

   Index State         Y2015
1  A     Alaska        1979143
2  C     Connecticut   1718072
3  D     Delaware      1627508
4  F     Florida       1170389
5  G     Georgia       1725470
6  H     Hawaii        1150882
7  I     Idaho         1757171
8  K     Kentucky      1913350
9  L     Louisiana     1403857
10 M     Missouri      1996005
11 N     New Hampshire 1963313
12 O     Oregon        1893515
13 P     Pennsylvania  1668232
14 R     Rhode Island  1611730
15 S     South Dakota  1136443
16 T     Texas         1705322
17 U     Utah          1729273
18 V     Virginia      1850394
19 W     Wyoming       1853858

<h3>Úlohy</h3>
    <div class="alert alert-info">
        <h4>Úloha 3.1</h4>
          <p> Z dát <samp> mtcars</samp> zobrazte počet automobilov pre každú hodnotu <samp>cyl</samp> (počet valcov) a usporiadajte zostupne. </p>
    </div>

In [59]:
mtcars
mtcars$cyl

arrange(mtcars, desc(cyl))

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

 [1] 6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 6 8 4

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

<div class="alert alert-info">
    <h4>Úloha 3.2</h4>
        <p> Vypočítajte podiel všetkých ulovených rýb v každom mesiaci. Dataset > <samp>RuffeSLRH92</samp>. Vykonajte tieto kroky:</p>
            <pre>install.packages("FSAdata")</pre>
            <pre>library(FSAdata)</pre>
               <ul>
               <li> zoskupenie údajov podľa mesiacov,</li>
               <li>zhrnutie počtu ulovených rýb v každom mesiaci,</li> 
               <li> pridania novej premennej, ktorá je pomerom celkovej hodnoty úlovok v každom mesiaci,</li>
               <li> triedenie výsledkov tak, aby bol ako prvý uvedený mesiac s najväčším úlovkom.</li>
              </ul>
<p>Výsledok:</p>
    <pre>
  ## month n priemer
  ## 1 7 182 0,24661
  ## 2 6 154 0,20867
  ## 3 9 126 0,17073
  ## 4 8 79 0,10705
  ## 5 10 69 0,09350
  ## 6 5 66 0,08943
  ## 7 4 62 0,08401</pre>
</div>

In [6]:
install.packages("FSAdata")
library(FSAdata)

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

## FSAdata v0.4.0. See ?FSAdata to find data for specific fisheries analyses.

In [ ]:
RuffleSLRH92 %>% 
group_by(month) %>%
summarise(

In [106]:
dataset = RuffeSLRH92
#dataset
names(dataset)
g = group_by(dataset, month)
c = count(g) #v kazdom mesace 
n = nrow(dataset) #spolu
#priemer = c/n
c
n
#mutate(c, priemer = median)
#summarise(g, c, priemer = c/n)

 [1] "fish.id"  "month"    "day"      "year"     "indiv"    "location"
 [7] "length"   "weight"   "sex"      "maturity" "age"

  month n
1  4     62
2  5     66
3  6    154
4  7    182
5  8     79
6  9    126
7 10     69

[1] 738

<h3>Úlohy na precvičenie</h3>
<div class="alert alert-success">
        <h4>Úloha 3.3</h4>
    <p>1. Načítajte si CSV data z URL: <samp>https://raw.githubusercontent.com/guru99-edu/R-Programming/master/travel_times.csv</samp></p>
    <p>2. Vyberte stĺpce <samp>GoingTo</samp> a <samp>DayOfWeek</samp> </p>
    <p>3. Odfiltrujte dáta, aby ste dostali iba výsledky s hodnotami <samp>Home</samp> a <samp>Wednesday</samp></p>
    <p>4. Zobrazte iba prvých 10 riadkov.</p>
    </div>

<div class="alert alert-success">
        <h4>Úloha 3.4</h4>
    <p>1. Načítajte si CSV data z URL: <samp>https://raw.githubusercontent.com/guru99-edu/R-Programming/master/travel_times.csv</samp></p>
    <p>2. Vyberte všetky stĺpce okrem <samp>Comments</samp></p>
    <p>3. Usporiadajte výsledok podľa stĺpcov <samp>Home</samp> a <samp>Distance</samp></p>
    <p>4. Zobrazte iba posledných 5 riadkov.</p>
    </div>