## Dátové typy a objekty
#### Objekty
Nové objekty môžeme vytvoriť a vypísať dvoma spôsobmi, je len na vás ktorí budete používať.

In [ ]:
# vytvaranie premennych
a <- 12
b = 1

In [ ]:
# vypis premennej 1. sposob
a

In [ ]:
# vypis premennej 2. sposob
print(b)

### Podmienky (Conditions)
Najčastejšie sa používajúce vektorové operácie:

| Podmienky  | Popis |
| :-- | ---  |
| `<- alebo =` | priradenie |
| `a == b`     | rovná sa |
| `a != b`     | nerovná sa |
| `a < b`      | je menšie ako |
| `a > b`      | je vačsie ako |
| `a <= b`     | je menšie rovné ako |
| `a => b`     | je väčšie rovné ako |
| `is.na()`    | testuje, či ide o chýbajúcu hodnotu NA (Not Available) |
| `is.nan()`   | testuje, či ide o NaN (Not A Number) t. j. o nedefinované (matematické) výsledky operácií |
| `is.null()`  | testuje, či objekt je NULL |

| Matematické operácie   | Popis |
| ---                    | ---   |
| `a+b, a-b, a*b, a/b`   | základné matematické operácie |
| `sum(x)`               | Suma |
| `min(x)`               | Najmenšia hodnota |
| `max(x)`               | Najväčšia hodnota |
| `mean(x)`              | Priemer |
| `median(x)`            | Stredná hodnota |
| `log(x)`               | Prirodzený logaritmus |
| `exp(x)`               | Exponencialna funkcia |
| `sqrt(x)`              | Druhá odmocnina |
| `abs(x)`               | Absolútna hodnota |
| `ceiling(x)`           | Zaokrúhli nahor na celé čislo |
| `floor(x)/trunc(x)`    | Zaokrúhli nadol na celé čislo |
| `round(x,digits = 5)`  | Zaokrúhli na 5 desatiných miest |
| `cislo %% 2 == 0`      | Zvyšok po delení dvoma je nula, t.j. čislo je deliteľné dvoma |
| `rnorm()`             | Náhodné normálne rozdelenie |
| `runif()`              | Náhodné rovnomerné rozdelenie |

### Vektory (Vector)
V prvej časti sa pozrieme akými spôsobmi sa dajú vektory vytvoriť. V druhej časti budeme pristupovať k jednotlivým elementom vektora podľa pozície a hodnoty, ktorú chceme vrátiť.

In [3]:
# vytvorenie ciselnych vektorov

v = c(5.5, 6.2, 7.8)  
 v
v = 10:30              
v
v = seq(1,5, by=0.2)  
v
v = rep(1:4, times=3) 
v
v = rep(1:4, each=3)  
v
print(v)

[1] 5.5 6.2 7.8

 [1] 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

 [1] 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0 3.2 3.4 3.6 3.8 4.0 4.2 4.4 4.6
[20] 4.8 5.0

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

In [4]:
# vytvorenie vektora logickych hodnot
v = c(TRUE, FALSE, FALSE) 
print(v)

[1]  TRUE FALSE FALSE

In [ ]:
# vytvorenie vektora znakov
v = c("ab", "cd", "ef")   
print(v)

In [5]:
vector = c(1, 6, 9, 12, 58, 13, 11, 89, 9)

# 1. PODLA POZICIE
print(vector[1])         # vrati prvy znak vektora

print(vector[-1])        # vrati vsetky znaky vektora okrem preveho

print(vector[1:4])       # vrati prve 4 znaky

print(vector[-(1:4)])    # vrati vsetky znaky okrem prevých styroch

print(vector[vector>6])  # vrati vacsie ako 6

[1] 1
[1]  6  9 12 58 13 11 89  9
[1]  1  6  9 12
[1] 58 13 11 89  9
[1]  9 12 58 13 11 89  9

In [6]:
# 2. PODLA HODNOTY
print(vector[vector == 9])  # vrati hodnoty rovné 9
print(vector[vector < 12]) # vrati hodnoty menšie ako 12

[1] 9 9
[1]  1  6  9 11  9

### Zmena dátového typu (Data Type) - explicitná korekcia
Poznáme niekoľko základných dátových typov a to: znaky (`character`), logické hodnoty (`logical`), numerické hodnoty (`numeric`), celočíselné hodnoty (`integer`), komplexné čísla (`complex`) a špeciálny dátový typ faktor (`factor`). Faktor sa používa na reprezentáciu kategorických dát. Niektoré algoritmy si vyžadujú zmenu dátového typu, preto si spôsob ako "pretypovať" nápriklad vektor hodnôt.

In [8]:
# uprava typu vektora - explicitna korekcia
z = 0:9  
z
class(z)
# zmena datoveho typu na numericky
n = as.numeric(z)
print(n)
class(n)

 [1] 0 1 2 3 4 5 6 7 8 9

[1] "integer"

 [1] 0 1 2 3 4 5 6 7 8 9

[1] "numeric"

In [ ]:
# zmena datoveho typu na logický - TRUE, FALSE
l = as.logical(z)
print(l)
class(l)

In [ ]:
# zmena datoveho typu na vektor znakov
ch = as.character(z) 
print(ch)
class(ch)

In [ ]:
# zmena datoveho typu na faktory
f = as.factor(z)
print(f)
class(f)

### Matice (Matrix)
Matice sú objekty typu vector s definovanými dimenziami. Existuje niekoľko spoôsobov ako vytvoriť maticu:

  <div class="alert alert-danger">
          <p>
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            Všimnte si ako sú matice konštruované!
          </p>
  </div>

In [9]:
# kedze matice su vlastne vektory s dimenziami, vieme ich vytvorit priamo s vektora a to:
# 1. pridanim dim()
L = c(10,3,5,1)
dim(L) = c(2,2)
print(L)

     [,1] [,2]
[1,]   10    5
[2,]    3    1

In [ ]:
L

In [10]:
# 2. pridanim stlpca
P = c(10,3,5,1)
R = c(1,6,2,9)

print(cbind(P,R))     # taketo pridavanie stlpcov a riadkov sa vyuziva aj pri data.frame

      P R
[1,] 10 1
[2,]  3 6
[3,]  5 2
[4,]  1 9

In [11]:
# 2. pridanim riadka
print(rbind(P,R))     # taketo pridavanie stlpcov a riadkov sa vyuziva aj pri data.frame

  [,1] [,2] [,3] [,4]
P   10    3    5    1
R    1    6    2    9

In [12]:
# R vsak ponuka vytvorenie matic jednoduchsie a to pomocou prikazu matrix
M = matrix(1:4,  nrow=2, ncol=2) 
print(M)

     [,1] [,2]
[1,]    1    3
[2,]    2    4

In [13]:
N = matrix(c(10,3,5,1), 2, 2)
print(N)

     [,1] [,2]
[1,]   10    5
[2,]    3    1

In [14]:
# pridanie nazvu pre tiadky a stlpce
dimnames(M) = list(c("a", "b"), c("c", "d")) 
print(M)

  c d
a 1 3
b 2 4

In [15]:
# pristup k podmnozinam
print(M[2, ])      # vyber druheho riadku

c d
2 4

In [16]:
print(M[ , 1])     # vyber prveho stlpca

a b
1 2

In [17]:
print(M[2, 1])     # vyber elementu v druhom riadku prvom stlpci

[1] 2

In [18]:
# informacie o matici
nrow(M)
ncol(M)
dim(M)

[1] 2

[1] 2

[1] 2 2

In [19]:
# zakladne operacie
M * N       # nasobenie po elementoch

  c  d
a 10 15
b  6  4

In [20]:
M %*% N     # skutocne nasobenie matic

  [,1] [,2]
a 19    8
b 32   14

In [21]:
solve(M,N)  # vrati x: m * x = n

  [,1]  [,2]
c -15.5 -8.5
d   8.5  4.5

### Zoznamy (List)
Zoznam je opäť špecialný objekt typu `vector`, avšak môže obsahovať rôzne dátové typy a objekty (napríklad znaky, čisla, logické hodnoty ale aj vnorený zoznam či vektor)

In [22]:
zoznam = list(a1 = 1:3, a2 = 0.3, a3 = "d",  a4=list(c(1,3),TRUE))
print(zoznam)

$a1
[1] 1 2 3

$a2
[1] 0.3

$a3
[1] "d"

$a4
$a4[[1]]
[1] 1 3

$a4[[2]]
[1] TRUE

In [23]:
# 1. vypise prvky elementu !!!! typ integer !!!!
z1 = zoznam[[1]]  # na prvej pozicii
print(z1)
class(z1)

[1] 1 2 3

[1] "integer"

In [24]:
z2 = zoznam$a1    # z nazvom elementu a2
print(z2)
class(z2)

[1] 1 2 3

[1] "integer"

In [25]:
# 2. vytvori NOVY ZOZNAM  !!!! typ list !!!!, ktory bude obsahovat:
z3 = zoznam["a2"]   # prvky elementu z nazvom a2
print(z3)
class(z3)

$a2
[1] 0.3

[1] "list"

In [26]:
z4 = zoznam[2]      # prvky elementu na druhej pozicii
print(z4)
class(z4)

$a2
[1] 0.3

[1] "list"

In [27]:
z5 = zoznam[c(1,3)] # prvky prveho a tretieho elementu povodneho zoznamu
print(z5)
class(z5)

$a1
[1] 1 2 3

$a3
[1] "d"

[1] "list"

### Dátové rámce (Data Frame)
Dátové rámce sa využívajú na ukladanie tabuľkových dát. Je to špeciálny typ zoznamu (list), pričom každý element má rovnakú dĺžku. Jeden element tvorí jeden stĺpec, pričom každý stĺpec môže nadobúdať iný dátový typ. Príkazom data.matrix() môžete konvertovať data na maticu.

In [28]:
# vytvorenie tabulky - data frames
df = data.frame(a1= 1:10, a2 = c(0.2, 0.7, 1.5, 2.2,3.4, 1, 2, 3, 6,9))

#View(df) - podporovane iba v R-studio
head(df)

  a1 a2
1 1  0.2
2 2  0.7
3 3  1.5
4 4  2.2
5 5  3.4
6 6  1.0

In [29]:
# informacie o data frame = rovnako ako pri maticiach 
nrow(df)
ncol(df)
dim(df)

[1] 10

[1] 2

[1] 10  2

V nasledujúcom skripte si ukážeme základné operácie s dátovými rámcami (prístup k podmnožinám, podmienený výber riadkov, nahrádzanie jednotlivých hodnôt, usporiadanie, pridávanie nových slĺpcov). Ďalej budeme k dátovým rámcom pristupovať cez knižnicu `dplyr`. Tejto knižnici bude venované `cvičenie 3`.

In [30]:
df = data.frame(x=1:5,y=rnorm(5),z=sample(11:15)) 
df

  x y          z
1 1  0.4433209 11
2 2 -0.7601022 15
3 3  0.4370237 13
4 4 -1.0035042 14
5 5  0.7621780 12

In [31]:
# pristup ku podmnozinam
df[ , 2]

[1]  0.4433209 -0.7601022  0.4370237 -1.0035042  0.7621780

In [32]:
df[,"x"]

[1] 1 2 3 4 5

In [33]:
df[2, ]

  x y          z
2 2 -0.7601022 15

In [34]:
df[2, 2]

[1] -0.7601022

In [35]:
df[1:2,"z"]

[1] 11 15

In [36]:
# podmienený výber riadkov
df[(df$x <= 3 | df$z > 15), ]

  x y          z
1 1  0.4433209 11
2 2 -0.7601022 15
3 3  0.4370237 13

In [37]:
# podmienený výber riadkov
df[which(df$x > 3), ]          # alebo df[df$x > 3, ]

  x y         z
4 4 -1.003504 14
5 5  0.762178 12

In [38]:
# nahradenie hodnôt
df$y[c(1,3)] = NA
df

  x y          z
1 1         NA 11
2 2 -0.7601022 15
3 3         NA 13
4 4 -1.0035042 14
5 5  0.7621780 12

In [39]:
# usporiadanie 
df[sort(df$x, decreasing = T), ]

  x y          z
5 5  0.7621780 12
4 4 -1.0035042 14
3 3         NA 13
2 2 -0.7601022 15
1 1         NA 11

In [40]:
# usporiadanie 
sort(df$x)    
sort(df$x,decreasing=TRUE)  
sort(df$y) 
sort(df$y,na.last=TRUE)

[1] 1 2 3 4 5

[1] 5 4 3 2 1

[1] -1.0035042 -0.7601022  0.7621780

[1] -1.0035042 -0.7601022  0.7621780         NA         NA

In [41]:
# pridanie noveho stlpca
df$new = c(1,5,9,6,10)
df

  x y          z  new
1 1         NA 11  1
2 2 -0.7601022 15  5
3 3         NA 13  9
4 4 -1.0035042 14  6
5 5  0.7621780 12 10

In [42]:
# pridanie noveho stlpca
df$new2 = df$x^2
df

  x y          z  new new2
1 1         NA 11  1   1
2 2 -0.7601022 15  5   4
3 3         NA 13  9   9
4 4 -1.0035042 14  6  16
5 5  0.7621780 12 10  25

In [43]:
# pridanie noveho stlpca
df$new3 = ifelse(df$x>3, TRUE, FALSE)  
df

  x y          z  new new2 new3
1 1         NA 11  1   1   FALSE
2 2 -0.7601022 15  5   4   FALSE
3 3         NA 13  9   9   FALSE
4 4 -1.0035042 14  6  16    TRUE
5 5  0.7621780 12 10  25    TRUE

### Podmienka if-else
Testovacia podmianka:

In [44]:
x = -2

if (x > 0) {
  print("Kladne cislo")
} else if (x < 0) {
  print("Zaporne cislo")
} else 
  print("Nula")

[1] "Zaporne cislo"

### Cyklus for
Cyklus s fixným počtom opkovaní:

In [45]:
# FOR
f = seq(1,100, by = 2)
a = NULL

for (i in 1:50)
{
  a[i] = f[i]^2
}
print(a)

 [1]    1    9   25   49   81  121  169  225  289  361  441  529  625  729  841
[16]  961 1089 1225 1369 1521 1681 1849 2025 2209 2401 2601 2809 3025 3249 3481
[31] 3721 3969 4225 4489 4761 5041 5329 5625 5929 6241 6561 6889 7225 7569 7921
[46] 8281 8649 9025 9409 9801

In [46]:
# for, next 
for(i in 40:60)
{
  if(i == 50)
  {
    next
  }
  print(i)
}

[1] 40
[1] 41
[1] 42
[1] 43
[1] 44
[1] 45
[1] 46
[1] 47
[1] 48
[1] 49
[1] 51
[1] 52
[1] 53
[1] 54
[1] 55
[1] 56
[1] 57
[1] 58
[1] 59
[1] 60

### Cyklus while
Cyklus, ktorý sa opakuje, pokiaľ je platná podmienka:

In [47]:
count = 0

while(count < 10)
{
  print(count)
  count = count + 1   
}

[1] 0
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9

### Break, repeat, next, return

| Príkaz | Popis |
| --- | --- |
|`repeat` | spúšťa nekonečný cyklus, ako while, bez podmienky |
|`break`  | ukončuje beh nekonečného cyklu |
|`next`   | preskočí iteráciu v cykle |
|`return` | výstup funkcie |

In [48]:
sum = 1 

repeat
{
  sum = sum + 2
  print(sum)
  if (sum > 11)
    break
}

[1] 3
[1] 5
[1] 7
[1] 9
[1] 11
[1] 13

### Funkcie

In [49]:
f1 = function(x) {
  x^2
}

f1(2) #volanie funkcie

[1] 4

In [50]:
f2 = function(x,y){
  x + y
  # x - y
  # x * y
  # x / y
}

f2(2,4)

[1] 6

### Úlohy

#### Úloha 1.1

Vytvorte funkciu s názvom `funkcia`, ktorá bude mať vstupný parameter `n`. Použitím cyklu prejdite všetky čísla od `1` po `n` a pomocou vetvenia urobte nasledovne operácie:

1. Ak sa jedná o číslo deliteľné 2 jeho druhú mocninu,
2. Ak sa jedná o číslo deliteľné 3 a zároveň 5 jeho tretiu mocninu.
3. Ak číslo nepatrí ani do jednej skupiny, tak ho iba vypíšte.

Na záver spustite funkciu s názvom funkcia.

In [51]:
funkcia = function(n){
    for(i in 1:n){
        if(i%%2==0){
            print(i^2)
        }
        else if(i%%3==0 & i%%5==0){
            print(i^3)
        }
        else{
            print(i)   
        }
    }
}
funkcia(10)

[1] 1
[1] 4
[1] 3
[1] 16
[1] 5
[1] 36
[1] 7
[1] 64
[1] 9
[1] 100